#!/bin/bash
#
# Usage:
#       ./cmd           : build a release version
#       ./cmd package   : run txsql_package.pl to make a package.

### set GCC_BASE to path of compiler, 
### eg: set 'GCC_BASE=/path' when gcc's path is '/path/bin/gcc'.
#gcc_path="/data1/git/software/tx-gcc"
gcc_path="/data1/compile/tgcc/tx-gcc-0.1-20220419"

tmp_dir=/data/tmp
base_dir=`pwd`
log_stage1="stage1_build.log"
log_stage2="stage2_build.log"
log_stage3="stage3_build.log"

# 'time' and 'stage2_time' should be same of compilation_optimize/runsysbench.sh.
time=300
stage2_time=120



show_env() {
    # check gcc environment.
    echo "GCC_BASE=${GCC_BASE}"
    which gcc g++ perf2bolt
    which sysbench
}

cleanup_env() {
    cd $base_dir || exit 2
    rm -rf bld
    rm -rf bld-debug
    rm -rf bld-release
    rm -f $log_stage1 $log_stage2 $log_stage3 2>/dev/null
    rm -f profile_data/*.gcda 2>/dev/null
    rm -f perf.data 2>/dev/null
    rm -f perf.fdata 2>/dev/null
    ps aux|grep compilation_optimize|grep "runtime_output_directory/mysqld"
    if [ $? -eq 0 ];then
        echo "mysqld exist, try to kill mysqld..."
        pid=`ps aux|grep compilation_optimize|grep "runtime_output_directory/mysqld"|awk '{print $2}'`
        kill -9 $pid
    fi

    # check.
    ps aux|grep compilation_optimize|grep "runtime_output_directory/mysqld"
    if [ $? -eq 0 ];then 
        echo "[error] Fail to kill mysqld, bye."
        exit 6
    fi
}

set_tmpdir() {
    if [ ! -d ${tmp_dir} ];then
        mkdir ${tmp_dir}
        if [ $? -ne 0 ];then
            echo "[error] Failed to create ${tmp_dir}"
            exit 4
        fi
    fi
    export TMPDIR=${tmp_dir}
}

stage1() {
    echo "=====Running stage1======"
    cd ${base_dir} && ./build.sh -t release --stage1  > ${log_stage1} 2>&1
    sleep 5

    # check
    if [ ! -f ${base_dir}/bld-release/runtime_output_directory/mysqld ];then
        echo "[error] Fail to generage mysqld, bye."
        exit 1
    fi
}

test1() {
    echo "=====Running test1======"
    ## initialize mysql
    cd compilation_optimize && sh init_mysqld.sh
    if [ $? -ne 0 ];then
        echo "[error] Fail to init mysqld, bye."
        exit 2
    fi
    sleep 5

    ## prepare data for test.
    sh runsysbench.sh prepare
    if [ $? -ne 0 ];then
        echo "[error] Fail to prepare data, bye."
        exit 2
    fi

    ## clean up profile-data which generated by stage1.
    if [ ! -d ${base_dir}/profile-data ];then
        echo "[error] Dir profile-data not exist, bye."
        exit 2
    fi 
    cd ${base_dir}/profile-data && rm -f *.gcda 2>/dev/null

    ## run sysbench test, it will takes serveral minutes. Default 5 mins.
    cd ../compilation_optimize && sh runsysbench.sh stage1
    ps axu|grep sysbench
    echo "[info] runnint test1, it may takes $((${time}+30))s ..."

    sleep $((${time}+30))

    ## shutdown mysqld.
    mysql -S /tmp/30002_txsql.sock -e "shutdown";
    sleep 3

    ## profile-data.
    du -sh ${base_dir}/profile-data

    # check
    if [ `cd ${base_dir} && ls profile-data/|wc -l` -lt 100 ];then
        echo "[error] Fail to generate profile-data, bye."
        exit 2
    fi 
}

stage2() {
    echo "=====Running stage2======"
    ## clean up environment.
    rm -rf bld
    rm -rf bld-debug
    rm -rf bld-release

    ## build.
    ./build.sh -t release --stage2  > ${log_stage2} 2>&1
    sleep 3

    # check
    if [ ! -f ${base_dir}/bld-release/runtime_output_directory/mysqld ];then
        echo "[error] Fail to generage mysqld, bye."
        exit 3
    fi
}

test2() {
    echo "=====Running test2======"
    ps aux|grep compilation_optimize|grep "runtime_output_directory/mysqld"
    if [ $? -ne 0 ];then
        ## start mysqld.
        cd ${base_dir}/compilation_optimize && sh init_mysqld.sh start
        sleep 5
    fi

    ## run sysbench test, generate perf.data.
    ## It will takes serveral minutes. Default 2 mins.
    cd ${base_dir}/compilation_optimize && sh runsysbench.sh stage2 &
    ps axu|grep sysbench
    echo "[info] running test2, it may takes $((${stage2_time}+30))s ..."
    sleep $((${stage2_time}+30))

    du -sh ${base_dir}/perf.data
    if [ $? -ne 0 ];then
        echo "[error] Fail to generate perf.data, bye."
        exit 4
    fi

    # check.
    expect_size=$((4*1024*1024)) # 4GB
    perf_size=`du -s ${base_dir}/perf.data|awk '{print $1}'`
    if [ ${perf_size} -lt ${expect_size} ];then
        echo "[error] perf.data too small(${perf_size}<${expect_size}), maybe not generate correctly, bye."
        exit 4
    fi

    ## shutdown mysqld.
    mysql -S /tmp/30002_txsql.sock -e "shutdown"

    ## convert perf.data.
    echo $TMPDIR
    cd ${base_dir} && perf2bolt bld-release/runtime_output_directory/mysqld -p perf.data -o perf.fdata
    if [ $? -ne 0 ];then 
        echo "[error] Fail to convert perf.fdata from perf.data, bye."
        exit 4
    fi
    sleep 3

    du -sh perf.fdata
}

stage3() {
    echo "=====Running stage3======"
    rm -rf bld
    rm -rf bld-debug
    rm -rf bld-release


    if [ "${1}x" == "packagex" ];then
        cd ${base_dir} && ./txsql_package.pl optimize  > ${log_stage3} 2>&1
        if [ $? -ne 0 ];then
            echo "[error] Fail to run stage3, bye."
            exit 5
        fi
    else 
        cd ${base_dir} && ./build.sh -t release --stage3 > ${log_stage3} 2>&1
        if [ $? -ne 0 ];then
            echo "[error] Fail to run stage3, bye."
            exit 5
        fi
    fi
}

##==================main====================================

# check gcc path.
if [ "${gcc_path}x" == "x" ];then
    echo "[error] 'gcc_path' not set or directory not exist, bye."
    exit 1
elif [ ! -d ${gcc_path} ];then
    echo "[error] 'gcc_path' $gcc_path not exist, bye."
    exit 1
fi

export GCC_BASE=${gcc_path}
export PATH=$GCC_BASE/bin:$GCC_BASE/bolt/bin:$PATH
export LD_LIBRARY_PATH=$GCC_BASE/lib64:$GCC_BASE/lib:$LD_LIBRARY_PATH

cleanup_env
set_tmpdir
stage1
test1
stage2
test2
stage3 $1

