#include <my_aes.h>

#include "mysqlbinlog_keyring.h"

#include "plugin/keyring_kms/checker/checker_factory.h"

#include "typelib.h"
#include "m_string.h"
#include "include/mysql/components/services/bits/mysql_rwlock_bits.h"
#include "../mysqlbinlog.h"
#include "tencentcloud/sts/v20180813/StsClient.h"
#include "tencentcloud/kms/v20190118/KmsClient.h"
#include "plugin/keyring_kms/common/json.h"

using namespace std;
using namespace TencentCloud;
using namespace TencentCloud::Sts::V20180813;
using namespace TencentCloud::Sts::V20180813::Model;
using namespace TencentCloud::Kms::V20190118;
using namespace TencentCloud::Kms::V20190118::Model;

mysql_rwlock_t LOCK_keyring;
mysql_mutex_t  LOCK_kms;

unordered_map<string, mysqlbinlog_key> g_hash_mysqlbinlog_key;

string keyring_file_version_2_0("Keyring file version:2.0");
bool is_kms = false;
string kms_error;

mysqlbinlog_key::mysqlbinlog_key():
  key_id(""), key_type(""), user_id(""), key(nullptr), key_len(0){}

mysqlbinlog_key::mysqlbinlog_key(const mysqlbinlog_key &T) {
  key_id = T.key_id;
  key_type = T.key_type;
  user_id = T.user_id;
  key.reset(new uchar[T.key_len]);
  memcpy(key.get(), T.key.get(), T.key_len);
  key_len = T.key_len;
}

mysqlbinlog_key& mysqlbinlog_key::operator=(const mysqlbinlog_key &T) {
  key_id = T.key_id;
  key_type = T.key_type;
  user_id = T.user_id;
  key.reset(new uchar[T.key_len]);
  memcpy(key.get(), T.key.get(), T.key_len);
  key_len = T.key_len;
  return *this;
}

/*
  The code in the mysqlbinlog_kms namespace is exactly just like the code of the same name in
  plugin/keyring_kms. The function of this space enables the client tool mysqlbinlog to parse
  the master key generated by the server-side keyring_kms plugin.
*/
namespace mysqlbinlog_kms {
  /** kms role type */
enum kms_role_type {
  /** No RoleType */
  KMS_ROLE_NONE = 0,
  /** Use SERVICEROLE */
  KMS_ROLE_SERVICEROLE = 1,
  /** Use SERVICELINKEDROLE */
  KMS_ROLE_SERVICELINKEDROLE = 2,

  KMS_ROLE_UNDEFINE = 3,
};

/** kms scheme type */
enum kms_scheme_type {
  /** No RoleType */
  KMS_SCHEME_NONE = 0,
  /** Use HTTPS */
  KMS_SCHEME_HTTPS = 1,
  /** Use HTTP */
  KMS_SCHEME_HTTP = 2,

  KMS_SCHEME_UNDEFINE = 3,
};

/** keyring kms variables. */
char *keyring_kms_file = nullptr;
char *keyring_kms_config = nullptr;
bool keyring_kms_check = false;
bool keyring_kms_dump = false;
bool keyring_kms_switch = false;
bool keyring_kms_verify = false;
bool keyring_kms_env = true;
bool keyring_kms_isprivate = false;
ulong keyring_kms_roletype = kms_role_type::KMS_ROLE_SERVICEROLE;
ulong keyring_kms_scheme = kms_scheme_type::KMS_SCHEME_HTTPS;

/** Last error in keyring kms */
string kms_error;

const string default_kms_key_alias = "KMS-TDSQL";
const string kms_key_desc =
      "The key is generated by CDB service when transparent data"  \
      " encryption is enabled.";

const string kms_key_usage = "ENCRYPT_DECRYPT";
const string kms_session_name = "cdb_keyring_kms";
const uint64_t kms_duration_seconds = 300;
const char*  kms_config_key_id = "kms_config_data";
const char*  kms_config_key_type = "AES";
const char*  kms_magic_key_id = "kms_magic_data";
const char*  kms_magic_key_type = "AES";

/** Key used to encrypt config & magic value in keyring_kms_file.
Note: We use AES_256, so encryption key len is 32 bytes. */
const char*  kms_encryption_key = "So36yeGJ1kOr9FdrOjuthJwVv9C4QFYf";
const uint32 kms_encryption_key_len = 32;

/** kms config mode */
enum config_mode {
  /** Use kms sdk 3.0 to access kms, region field is set*/
  KMS_CONFIG_NON_USER_DEFINED = 0,

  /** Use kms sdk 3.0 to access kms, user_key_id field is added based
   on mode KMS_CONFIG_NON_USER_DEFINED config. */
  KMS_CONFIG_USER_DEFINED = 1,

  KMS_CONFIG_UNINITIALIZED
};

/** keyring kms version, reserved for latter upgrade */
enum keyring_kms_version {
  /** keyring_kms_version 1, which :
     (1) use kms 3.0 to access kms;
     (2) supports user defined and non-user-defined modes */
  KEYRING_KMS_VERSION_1 = 0
};

/** structure of kms config params */
struct kms_config_t {
  /** Secret key used by cdb to get session token from cam */
  string secret_key;

  /** Secret id used by cdb to get session token from cam */
  string secret_id;

  /** Kms domain name to be accessed by cdb */
  string end_point;

  /** Cam domain name to be accessed by cdb */
  string cam_point;

  /** Role name used by cdb to get session token from cam */
  string role_name;

  /** Uin used by cdb to get session token from cam */
  string uin;

  /** Region of kms service to be accessed */
  string region;

  /** User defined CM key id to be used to generate/decrypt data key */
  string user_key_id;

  /** Role type is used to construct kms requests */
  string role_type;

  /** scheme type is used to construct kms requests */
  string scheme_type;

  /** Whether the kms service access is privatization */
  string is_private;

  /** Mode of current kms config */
  config_mode cfg_mode;

  /** Version of keyring kms */
  keyring_kms_version version;
};

/** kms configuration in use. */
kms_config_t kms_config = kms_config_t
{
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  KMS_CONFIG_UNINITIALIZED,
  KEYRING_KMS_VERSION_1
};

static inline bool is_base64(unsigned char c) {
  return (isalnum(c) || (c == '+') || (c == '/'));
}

std::string base64_decode(std::string const& encoded_string) {
  int   in_len = encoded_string.size();
  int   i = 0;
  int   j = 0;
  int   in_ = 0;
  std::string                 ret;
  static const  std::string   base64_chars=
	  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  unsigned char               char_array_4[4], char_array_3[3];

  while (in_len-- && ( encoded_string[in_] != '=')
         && is_base64(encoded_string[in_])) {
    char_array_4[i++] = encoded_string[in_]; in_++;
    if (i ==4) {
      for (i = 0; i <4; i++) {
        char_array_4[i] = base64_chars.find(char_array_4[i]);
      }

      char_array_3[0] = (char_array_4[0] << 2) + ((char_array_4[1] & 0x30) >> 4);
      char_array_3[1] = ((char_array_4[1] & 0xf) << 4) + ((char_array_4[2] & 0x3c) >> 2);
      char_array_3[2] = ((char_array_4[2] & 0x3) << 6) + char_array_4[3];

      for (i = 0; (i < 3); i++) {
        ret += char_array_3[i];
      }

      i = 0;
    }
  }

  if (i) {
    for (j = i; j <4; j++) {
      char_array_4[j] = 0;
    }

    for (j = 0; j <4; j++) {
      char_array_4[j] = base64_chars.find(char_array_4[j]);
    }

    char_array_3[0] = (char_array_4[0] << 2) + ((char_array_4[1] & 0x30) >> 4);
    char_array_3[1] = ((char_array_4[1] & 0xf) << 4) + ((char_array_4[2] & 0x3c) >> 2);
    char_array_3[2] = ((char_array_4[2] & 0x3) << 6) + char_array_4[3];

    for (j = 0; (j < i - 1); j++) {
      ret += char_array_3[j];
    }
  }

  return ret;
}

const char *kering_kms_role_type_names[] = {
    "NONE", "ServiceRole", "ServiceLinkedRole", NullS};
static TYPELIB keyring_kms_role_typelib = {
    kms_role_type::KMS_ROLE_UNDEFINE, "keyring_kms_role_typelib",
    kering_kms_role_type_names, NULL};

const char *kering_kms_scheme_type_names[] = {
    "NONE", "HTTPS", "HTTP", NullS};
static TYPELIB keyring_kms_scheme_typelib = {
    kms_scheme_type::KMS_SCHEME_UNDEFINE, "keyring_kms_scheme_typelib",
    kering_kms_scheme_type_names, NULL};

int set_stsclient_profile(StsClient &sts_client) {
  HttpProfile tmp_http_profile = sts_client.GetClientProfile().GetHttpProfile();
  tmp_http_profile.SetProtocol(HttpProfile::Scheme::HTTP);
  ClientProfile tmp_client_profile = sts_client.GetClientProfile();
  tmp_client_profile.SetHttpProfile(tmp_http_profile);
  sts_client.SetClientProfile(tmp_client_profile);
  return 0;
}

int kms_get_session_token(string& session_token,
                          string& secret_id,
                          string& secret_key) {

  Credential cred = Credential(kms_config.secret_id, kms_config.secret_key);

  AssumeRoleRequest assume_req = AssumeRoleRequest();
  string roleArn = "qcs::cam::uin/";
  roleArn.append(kms_config.uin);

  switch (keyring_kms_roletype) {
  case kms_role_type::KMS_ROLE_SERVICELINKEDROLE:
      roleArn.append(":role/tencentcloudServiceRoleName/");
      break;
  case kms_role_type::KMS_ROLE_SERVICEROLE:
      roleArn.append(":roleName/");
      break;
  default:
      roleArn.append(":roleName/");
      break;
  }

  roleArn.append(kms_config.role_name);
  assume_req.SetRoleArn(roleArn);
  assume_req.SetRoleSessionName(kms_session_name);
  assume_req.SetDurationSeconds(kms_duration_seconds);
  StsClient sts_client = StsClient(cred, kms_config.region);
  sts_client.SetEndPoint(kms_config.cam_point);

  if (keyring_kms_scheme == kms_scheme_type::KMS_SCHEME_HTTP) {
    set_stsclient_profile(sts_client);
  }

  auto outcome = sts_client.AssumeRole(assume_req);
  if (!outcome.IsSuccess()) {
    kms_error = "AssumeRole fail:" + outcome.GetError().PrintAll();
    error("%s.", kms_error.c_str());
    return 1;
  }

  AssumeRoleResponse assume_rsp = outcome.GetResult();
  Credentials tmp_cred = assume_rsp.GetCredentials();

  session_token = tmp_cred.GetToken();
  secret_id = tmp_cred.GetTmpSecretId();
  secret_key = tmp_cred.GetTmpSecretKey();
  return 0;
}

/** Set the credential  of kmsclient */
int kms_structure_cred(Credential& cred){
  if (keyring_kms_isprivate) {
    cred.SetSecretId(kms_config.secret_id);
    cred.SetSecretKey(kms_config.secret_key);
  } else {
    /* Get session token from cam. */
    string session_token;
    string secret_id;
    string secret_key;
    if (kms_get_session_token(session_token, secret_id, secret_key)) {
      return 1;
    }
    cred.SetSecretId(secret_id);
    cred.SetSecretKey(secret_key);
    cred.SetToken(session_token);
  }

  return 0;
}

int set_kmsclient_profile(KmsClient& kms_client){
  HttpProfile tmp_http_profile = kms_client.GetClientProfile().GetHttpProfile();
  tmp_http_profile.SetProtocol(HttpProfile::Scheme::HTTP);
  ClientProfile tmp_client_profile = kms_client.GetClientProfile();
  tmp_client_profile.SetHttpProfile(tmp_http_profile);
  kms_client.SetClientProfile(tmp_client_profile);

  return 0;
}

int kms_list_key_detail(std::string &cm_key_id){
  assert(kms_config.cfg_mode != KMS_CONFIG_UNINITIALIZED);
  Credential cred = Credential("","","");

  if (kms_structure_cred(cred)) {
    return 1;
  }

  KmsClient kms_client = KmsClient(cred, kms_config.region);
  kms_client.SetEndPoint(kms_config.end_point);

  if (keyring_kms_scheme == kms_scheme_type::KMS_SCHEME_HTTP) {
    set_kmsclient_profile(kms_client);
  }

  ListKeyDetailRequest list_key_req = ListKeyDetailRequest();
  list_key_req.SetOffset(0);
  list_key_req.SetLimit(10);

  if (kms_config.cfg_mode == KMS_CONFIG_USER_DEFINED) {
    /** set role to 0 to list key created by user itself */
    list_key_req.SetRole(0);

    /** if current kms config is user defined key, we user cm key id
    to listkeydetail*/
    list_key_req.SetSearchKeyAlias(kms_config.user_key_id);
  } else if (kms_config.cfg_mode == KMS_CONFIG_NON_USER_DEFINED) {
    /** set role to 1 to list key created by privilege granted  user*/
    list_key_req.SetRole(1);
    list_key_req.SetSearchKeyAlias(default_kms_key_alias);
  } else {
    kms_error = "ListKeyDetail fail because kms config is not set";
    error("%s.", kms_error.c_str());
    return 1;
  }

  auto list_key_res = kms_client.ListKeyDetail(list_key_req);
  if (!list_key_res.IsSuccess()) {
    kms_error = "ListKeyDetail fail:" + list_key_res.GetError().PrintAll();
    error("%s.", kms_error.c_str());
    return 1;
  }

  ListKeyDetailResponse list_key_rsp = list_key_res.GetResult();
  std::vector<KeyMetadata> metas;
  KeyMetadata key_meta;

  metas = list_key_rsp.GetKeyMetadatas();

  cm_key_id = "";
  for (unsigned int i = 0; i < metas.size(); i++) {
    key_meta = metas[i];
    if ((kms_config.cfg_mode == KMS_CONFIG_NON_USER_DEFINED
         && key_meta.GetAlias() == default_kms_key_alias)
         || (kms_config.cfg_mode == KMS_CONFIG_USER_DEFINED
         && key_meta.GetKeyId() == kms_config.user_key_id)) {
      cm_key_id = key_meta.GetKeyId();
      break;
    }
  }

  return 0;
}

int kms_config_check() {
  std::string   cm_key_id;
  if (kms_list_key_detail(cm_key_id)) {
    return 1;
  }

  /* If we use user defined cm key, we should guarantee that cm key exists.*/
  if (kms_config.cfg_mode == KMS_CONFIG_USER_DEFINED) {
    if (cm_key_id.length() != 0) {
      return 0;
    } else {
      kms_error = "Can't find cmkey , id: " + kms_config.user_key_id;
      error("%s.", kms_error.c_str());
      return 1;
    }
  }

  return 0;
}

int parse_and_set_role(string& role_type){
  int type = find_type(role_type.c_str(), &keyring_kms_role_typelib,
                       FIND_TYPE_NO_PREFIX);
  /* Set "none" is invalid */
  if (type <= 1) {
    return 1;
  }
  keyring_kms_roletype = static_cast<ulong>(type - 1);

  return 0;
}

int parse_and_set_scheme(string& scheme_type){
  int type = find_type(scheme_type.c_str(), &keyring_kms_scheme_typelib,
                       FIND_TYPE_NO_PREFIX);
  if (type <= 1) {
    return 1;
  }
  keyring_kms_scheme = static_cast<ulong>(type - 1);

  return 0;
}


int kms_decrypt(const std::string encrypted_key, std::string &plain_key) {
  Credential cred = Credential("","","");

  if (kms_structure_cred(cred)) {
    return 1;
  }
  KmsClient kms_client = KmsClient(cred, kms_config.region);
  kms_client.SetEndPoint(kms_config.end_point);

  if (keyring_kms_scheme == kms_scheme_type::KMS_SCHEME_HTTP) {
    set_kmsclient_profile(kms_client);
  }

  DecryptRequest decrypt_req = DecryptRequest();
  decrypt_req.SetCiphertextBlob(encrypted_key);
  decrypt_req.SetEncryptionContext("");
  auto decrypt_res = kms_client.Decrypt(decrypt_req);
  if (!decrypt_res.IsSuccess()) {
    kms_error = "Decrypt fail:" + decrypt_res.GetError().PrintAll();
    error("%s.", kms_error.c_str());
    return 1;
  }

  DecryptResponse decrypt_rsp = decrypt_res.GetResult();
  plain_key = base64_decode(decrypt_rsp.GetPlaintext());
  return 0;
}


int parse_kms_config(string kms_config_data, config_mode &old_mode)
{
  /* 1. parse kms config data*/
  Json::Reader reader;
  Json::Value  data;
  if (!reader.parse(kms_config_data, data)) {
    return 1;
  }

  /* 2. check kms config data*/
  string kms_secret_key_data = data["secret_key"].asString();
  string kms_secret_id_data = data["secret_id"].asString();
  string kms_end_point_data = data["kms_endpoint"].asString();
  string kms_cam_point_data = data["cam_endpoint"].asString();
  string kms_role_name_data = data["role_name"].asString();
  string kms_uin_data = data["uin"].asString();
  string kms_region_data = data["region"].asString();
  string kms_user_key_id_data = data["user_key_id"].asString();
  string kms_role_type_data = data["role_type"].asString();
  string kms_scheme_type_data = data["scheme_type"].asString();
  string kms_is_private_data = data["is_private"].asString();

  if (kms_is_private_data.length() > 1 || (kms_is_private_data.length() == 1
      && kms_is_private_data != "0" && kms_is_private_data != "1")) {
    return 1;
  }
  bool tmp_is_private_data = false;
  if (kms_is_private_data.length() == 1 && kms_is_private_data == "1") {
    tmp_is_private_data = true;
  }
  old_mode = kms_config.cfg_mode;

  if (kms_secret_key_data.length() == 0 || kms_secret_id_data.length() == 0
      || kms_end_point_data.length() == 0) {
    return 1;
  }
  if (!tmp_is_private_data) {
    if (kms_cam_point_data.length() == 0 || kms_role_name_data.length() == 0
        || kms_uin_data.length() == 0 || kms_region_data.length() == 0) {
      return 1;
    }
  } else {
    kms_region_data = "";
  }

  ulong tmp_keyring_kms_roletype = keyring_kms_roletype;
  if (kms_role_type_data.length() != 0) {
    if (parse_and_set_role(kms_role_type_data)){
      return 1;
    }
  } else {
    keyring_kms_roletype = kms_role_type::KMS_ROLE_SERVICEROLE;
  }
  if (kms_scheme_type_data.length() != 0) {
    if (parse_and_set_scheme(kms_scheme_type_data)) {
        keyring_kms_roletype = tmp_keyring_kms_roletype;
        return 1;
    }
  } else {
    keyring_kms_scheme = kms_scheme_type::KMS_SCHEME_HTTPS;
  }

  /* 3. judge kms config mode. */
  if ( kms_user_key_id_data.length() == 0) {
    kms_config.cfg_mode = KMS_CONFIG_NON_USER_DEFINED;
    kms_config.user_key_id = "";
  } else {
    kms_config.cfg_mode = KMS_CONFIG_USER_DEFINED;
    kms_config.user_key_id = kms_user_key_id_data;
  }

  /* 4. set global kms config. */
  keyring_kms_isprivate = tmp_is_private_data;
  kms_config.secret_key = kms_secret_key_data;
  kms_config.secret_id = kms_secret_id_data;
  kms_config.end_point = kms_end_point_data;
  kms_config.cam_point = kms_cam_point_data;
  kms_config.role_name = kms_role_name_data;
  kms_config.uin = kms_uin_data;
  kms_config.region = kms_region_data;
  kms_config.version = KEYRING_KMS_VERSION_1;
  kms_config.role_type = kms_role_type_data;
  kms_config.scheme_type =kms_scheme_type_data;
  kms_config.is_private = kms_is_private_data;

  return 0;
}

int parse_and_set_kms_config_data(string& kms_config_data)
{
  /* 1. preserve cur kms config */
  kms_config_t tmp_kms_config = kms_config;

  /* 2. parse kms config */
  config_mode old_config_mode;
  int ret;
  ret = parse_kms_config(kms_config_data, old_config_mode);
  if (ret) {
    kms_config = tmp_kms_config;
    return 1;
  }

  /* 3. check new kms config mode to confirm that kms config mode
        was not set back */
  if (old_config_mode != KMS_CONFIG_UNINITIALIZED
      && kms_config.cfg_mode < old_config_mode) {
    kms_config = tmp_kms_config;
    return 1;
  }

  /* 4. Check if config works. */
  if (kms_config_check()) {
    return 1;
  }
  return 0;
}

bool set_kms_config_and_decrypt_master_key() {
  for (auto &val : g_hash_mysqlbinlog_key){
    if (val.second.key_id == mysqlbinlog_kms::kms_config_key_id) {
      int elen;
      unsigned char *des_key = new unsigned char[val.second.key_len * 3];
      memset(des_key, 0, val.second.key_len * 3);
      elen = my_aes_decrypt(static_cast<unsigned char*>(val.second.key.get()),
                            val.second.key_len,
                            des_key,
                            reinterpret_cast<unsigned char*>(const_cast<char *>(mysqlbinlog_kms::kms_encryption_key)),
                            mysqlbinlog_kms::kms_encryption_key_len,
                            my_aes_256_ecb,
                            nullptr,
                            true);
      if (elen == MY_AES_BAD_DATA) {
        error("Cloud not aes_decrypt kms config data.");
        delete[] des_key;
        return true;
      }
      string config_str = string((char*)(des_key), elen);
      if (parse_and_set_kms_config_data(config_str)) {
        error("Cloud not parse or set kms config data.");
        delete[] des_key;
        return true;
      }
      delete[] des_key;
    }
  }

  for (auto &val : g_hash_mysqlbinlog_key){
    if (val.second.key_id == mysqlbinlog_kms::kms_config_key_id || val.second.key_id == mysqlbinlog_kms::kms_magic_key_id)
      continue;

    string kms_encrypted_key((char*)(val.second.key.get()), val.second.key_len);
    string kms_plain_key;
    if (kms_decrypt(kms_encrypted_key, kms_plain_key)) {
      error("Cloud not decrypt kms encrypted key.");
      return true;
    }

    val.second.key_len = kms_plain_key.length();
    val.second.key.reset(new uchar[val.second.key_len]);
    memset(val.second.key.get(), 0, val.second.key_len);
    strncpy(reinterpret_cast<char*>(val.second.key.get()), kms_plain_key.c_str(), val.second.key_len);
  }
  return false;
}

};
/* end of namespace mysqlbinlog_kms */

bool load_field_size(const uchar *buffer, size_t *buffer_position,
                          size_t key_pod_size, size_t *field_length) {
  if (key_pod_size < *buffer_position + sizeof(size_t)) return true;
  *field_length = *reinterpret_cast<const size_t *>(buffer + *buffer_position);
  *buffer_position += sizeof(size_t);

  return false;
}

bool load_string_from_buffer(const uchar *buffer, size_t *buffer_position,
                                  size_t key_pod_size, string *string,
                                  size_t string_length) {
  if (key_pod_size < *buffer_position + string_length) return true;

  string->assign(reinterpret_cast<const char *>(buffer) + *buffer_position,
                 string_length);
  *buffer_position += string_length;

  return false;
}

bool load_from_buffer(uchar *buffer,
                      size_t *number_of_bytes_read_from_buffer,
                      size_t input_buffer_size) {
  size_t key_pod_size;
  size_t key_id_length;
  size_t key_type_length;
  size_t user_id_length;
  size_t buffer_position = 0;

  if (input_buffer_size < buffer_position + sizeof(size_t)) return true;

  key_pod_size = *reinterpret_cast<size_t *>(buffer + buffer_position);

  if (input_buffer_size < buffer_position + key_pod_size) return true;

  buffer_position += sizeof(size_t);
  mysqlbinlog_key cur_key;
  if (load_field_size(buffer, &buffer_position, key_pod_size, &key_id_length) ||
      load_field_size(buffer, &buffer_position, key_pod_size,
                      &key_type_length) ||
      load_field_size(buffer, &buffer_position, key_pod_size,
                      &user_id_length) ||
      load_field_size(buffer, &buffer_position, key_pod_size, &cur_key.key_len))
    return true;
  if (load_string_from_buffer(buffer, &buffer_position, key_pod_size, &cur_key.key_id,
                              key_id_length) ||
      load_string_from_buffer(buffer, &buffer_position, key_pod_size, &cur_key.key_type,
                              key_type_length) ||
      load_string_from_buffer(buffer, &buffer_position, key_pod_size, &cur_key.user_id,
                              user_id_length))
    return true;
  cur_key.key.reset(new uchar[cur_key.key_len]);
  memcpy(cur_key.key.get(), buffer + buffer_position, cur_key.key_len);
  buffer_position += cur_key.key_len;

  size_t padding =
      (sizeof(size_t) - (buffer_position % sizeof(size_t))) % sizeof(size_t);
  buffer_position += padding;

  *number_of_bytes_read_from_buffer = buffer_position;
  g_hash_mysqlbinlog_key[cur_key.key_id] = cur_key;

  return false;
}

bool load_file_into_buffer(FILE *file){
  /* keyring_kms has the same logic as keyring in load_file_into_buffer(), there use keyring_kms source code*/

  /* 1.only read the data of key into buffer*/
  fseek(file, 0L, SEEK_END);
	size_t file_size = ftell(file);
	size_t input_buffer_size = file_size - keyring_kms::Checker::EOF_TAG_SIZE - keyring_file_version_2_0.length() - SHA256_DIGEST_LENGTH;
	fseek(file , keyring_file_version_2_0.length(), SEEK_SET);
  unique_ptr<uchar[]> tmp = make_unique<uchar[]>(input_buffer_size);
	auto res [[maybe_unused]] = fread(tmp.get(), input_buffer_size, 1, file);

  /* 2.checks whether keyring file matches any known keyring file structure */
  keyring_kms::CheckerFactory checker_factory;
  auto checker = checker_factory.getCheckerForVersion(keyring_file_version_2_0);
  keyring_kms::Converter::Arch file_arch(keyring_kms::Converter::Arch::UNKNOWN);
  keyring_kms::Converter::Arch native_arch(keyring_kms::Converter::get_native_arch());
  keyring_kms::Digest digest(keyring_kms::DigestKind::SHA256, keyring_kms::dummy_digest);
  if(checker->check_file_structure(fileno(file), file_size, &digest, &file_arch)) {
    return true;
  };

  /* 3.if machine architecture of the input key data is not same as current machine architecture, convert it */
  std::string converted;
  if(file_arch != native_arch){
    keyring_kms::Converter::convert_data(reinterpret_cast<const char *>(tmp.get()),
                                  input_buffer_size, file_arch, native_arch,
                                  converted);
    tmp.release();
    tmp = make_unique<uchar[]>(converted.length());
    memcpy(tmp.get(), converted.c_str(), converted.length());
  }

  /* 4. Parse the mysqlbinlog_key structure from the buffer */
	size_t position = 0;
  size_t number_of_bytes_read_from_buffer = 0;
	while(position < input_buffer_size &&
        load_from_buffer(tmp.get() + position, &number_of_bytes_read_from_buffer, input_buffer_size - position) == false) {
    position += number_of_bytes_read_from_buffer;
  };
  return false;
}

void xor_data() {
  static const char *obfuscate_str = "*305=Ljt0*!@$Hnm(*-9-w;:";
  for (auto &val : g_hash_mysqlbinlog_key) {
    for (size_t i = 0, l = 0; i < val.second.key_len;
      ++i, l = ((l + 1) % strlen(obfuscate_str)))
      val.second.key.get()[i] ^= obfuscate_str[l];

    if (val.second.key_id == mysqlbinlog_kms::kms_config_key_id)
      is_kms = true;
  }
}

/*  Decrypted entry function, used to initialize the keyring hash map */
bool init_mysqlbinlog_key(std::string file_name){
	FILE* keyring_file = nullptr;
	keyring_file = fopen(file_name.c_str(), "r");
  if (keyring_file == nullptr) {
    error("Could not open keyring file %s.", file_name.c_str());
    return true;
  }
  /* 1.read keyring in buffer */
	if (load_file_into_buffer(keyring_file)) {
    fclose(keyring_file);
    error("%s is malformed.", file_name.c_str());
    return true;
  }
	fclose(keyring_file);
  /* 2.XOR conversion */
	xor_data();
  /* 3.if keyring_file has "kms_config_data", decrypt key data */
  if (is_kms && mysqlbinlog_kms::set_kms_config_and_decrypt_master_key()) {
    return true;
  }
  return false;
}
