#include "my_config.h"
#include "my_dbug.h"
#include <my_aes.h>
#include "keyring.h"
#include "keyring_kms.h"
#include "keyring_memory.h"
#include <string>
#include <map>
#include <iostream>
#include "tencentcloud/kms/v20190118/KmsClient.h"
#include "tencentcloud/sts/v20180813/StsClient.h"
#include "json.h"

using namespace std;
using namespace TencentCloud;
using namespace TencentCloud::Sts::V20180813;
using namespace TencentCloud::Sts::V20180813::Model;
using namespace TencentCloud::Kms::V20190118;
using namespace TencentCloud::Kms::V20190118::Model;

#define MAX_CONFIG_VALUE_LEN 512

/** keyring kms variables. */
char *keyring_kms_file = nullptr;
char *keyring_kms_config = nullptr;
bool keyring_kms_check = false;

/** kms configuration in use. */
string kms_secret_id;
string kms_secret_key;
string kms_end_point;
string kms_region;

/** Last error in keyring kms */
string kms_error;

/** kms acation: 1.create_key 2.generate_data_key 3.decrypt 4.list_key_details 5.assume_role */
string kms_action;

/** Flag whether kms config is set properly. */
bool  is_kms_config_set = false;

/** Alias of cm key used by txsql to generate data key. If this cm key was deleted,
    encrypted table and binlog will not be accessable. User should be responsible
    for safety of this cm key. */
const string kms_key_alias = "TXSQL-KMS";
const string kms_key_desc = "The key is generated by TXSQL service when transparent data encryption is enabled.";
const string kms_key_usage = "ENCRYPT_DECRYPT";
const char*  kms_config_key_id = "kms_config_data";
const char*  kms_config_key_type = "AES";

/** Check kms config status */
int kms_config_check();

/** kms key cache item */
struct key_item {
  string key;
  string key_type;
  string user_id;
};

/** kms key cache map */
map<string, key_item> kms_key_map;

/** Fetch key from key cache map by key id
@param[in]  key_id    key id
@param[out] key_type  key type (unused)
@param[out] user_id   user id (unused)
@param[out] key       key
@param[out] key_len   key length
@return 0 on success, 1 on failure  */
int key_cache_fetch(const char *key_id,
                    char **key_type,
                    const char *user_id MY_ATTRIBUTE((unused)),
                    void **key,
                    size_t *key_len) {
  string id = key_id;
  int ret = 1;

  mysql_mutex_lock(&LOCK_kms);

  map<string, key_item>::iterator it;
  it = kms_key_map.find(id);
  if (it != kms_key_map.end()) {
    key_item item = it->second;
    string kms_key = item.key;

    *key_len = kms_key.length();
    *key = my_malloc(PSI_NOT_INSTRUMENTED, *key_len, MYF(MY_WME));
    strncpy(static_cast<char*>(*key), kms_key.c_str(), *key_len);

    *key_type = static_cast<char*>(my_malloc(PSI_NOT_INSTRUMENTED,
			    item.key_type.length() + 1, MYF(MY_WME)));
    strncpy(*key_type, item.key_type.c_str(), item.key_type.length());
    (*key_type)[item.key_type.length()] = '\0';

    ret = 0;
  }

  mysql_mutex_unlock(&LOCK_kms);

  return ret;
}

/** remove key from key cache map by key id
@param[in]  key_id    key id
@param[in]  user_id   user id (unused)
*/
void key_cache_remove(const char *key_id,
                      const char *user_id MY_ATTRIBUTE((unused))) {
  mysql_mutex_lock(&LOCK_kms);

  map<string, key_item>::iterator it;
  it = kms_key_map.find(string(key_id));
  if (it != kms_key_map.end()) {
    kms_key_map.erase(it);
  }

  mysql_mutex_unlock(&LOCK_kms);
}

/** Store key into key cache map
[key id]--->[key, key type, user id]
@param[in] key_id    key id
@param[in] key_type  key type
@param[in] user_id   user id
@param[in] key       key
@param[in] key_len   key len
@return 0 on success, 1 on failure  */
int key_cache_store(const char *key_id, char *key_type, const char *user_id,
                    void *key, size_t key_len) {
  mysql_mutex_lock(&LOCK_kms);

  /* To avoid map growing too big. */
  if (kms_key_map.size() > 100) {
    kms_key_map.clear();
  }

  string key_str((char*)key, key_len);

  key_item  item;
  item.key = key_str;
  item.key_type = key_type;
  item.user_id = (user_id == nullptr) ? "" : user_id;

  string id = key_id;
  kms_key_map.insert(pair<string, key_item>(id, item));

  mysql_mutex_unlock(&LOCK_kms);

  return 0;
}

/** Parse config data and set to global variables on success
@param[in] kms_config_data   kms config data in json format
@return 0 on success, 1 on failure */
int parse_and_set_kms_config_data(string& kms_config_data) {
  /* 1. Check config json format. */
  Json::Reader reader;
  Json::Value  data;
  if (!reader.parse(kms_config_data, data)) {
    return 1;
  }

  /* 2. Check if all members are set. */
  string kms_secret_key_data = data["secret_key"].asString();
  string kms_secret_id_data = data["secret_id"].asString();
  string kms_end_point_data = data["kms_endpoint"].asString();
  string kms_region_data = data["region"].asString();

  if (kms_secret_key_data.length() == 0 || kms_secret_id_data.length() == 0
      || kms_end_point_data.length() == 0 || kms_region_data.length() == 0 ) {
    logger->log(MY_ERROR_LEVEL, "One or more fields are null when parsing config.");
    return 1;
  }

  string kms_secret_key_org = kms_secret_key;
  string kms_secret_id_org = kms_secret_id;
  string kms_end_point_org = kms_end_point;
  string kms_region_org = kms_region;

  kms_secret_key = kms_secret_key_data;
  kms_secret_id = kms_secret_id_data;
  kms_end_point = kms_end_point_data;
  kms_region = kms_region_data;

  /* 3. Check if config works. */
  if (kms_config_check()) {
    kms_secret_key = kms_secret_key_org;
    kms_secret_id = kms_secret_id_org;
    kms_end_point = kms_end_point_org;
    kms_region = kms_region_org;

    return 1;
  }

  is_kms_config_set = true;

  return 0;
}

/** Load config data from kms file. */
int load_kms_config_data() {
  void*  kms_config_value;
  size_t kms_config_value_len;
  char*  key_type = nullptr;
  int    ret;
  string kms_config_str;

  ret = mysql_key_fetch<keyring_kms::Key>(kms_config_key_id,
                                          &key_type, nullptr,
                                          &kms_config_value,
                                          &kms_config_value_len,
                                          "keyring_kms");
  if (ret || kms_config_value == nullptr) {
    return 1;
  }

  kms_config_str = string(static_cast<char*>(kms_config_value), kms_config_value_len);
  my_free(kms_config_value);
  my_free(key_type);

  if (parse_and_set_kms_config_data(kms_config_str)) {
    return 1;
  }

  logger->log(MY_INFORMATION_LEVEL, "Load keyring kms config data successfully!");

  return 0;
}

/** Check and store kms config data when setting
@param[in]  thd   mysql thread instance, unused
@param[in]  var   variable, unused
@param[out] save  saved value
@param[in]  value original value
@return 0 on success, 1 on failure */
int check_kms_config_data(MYSQL_THD thd  MY_ATTRIBUTE((unused)),
                          SYS_VAR *var  MY_ATTRIBUTE((unused)),
                          void *save, st_mysql_value *value) {
  char            buff[MAX_CONFIG_VALUE_LEN + 1];
  int             len = sizeof(buff);

  string kms_config_data = value->val_str(value, buff, &len);

  mysql_mutex_lock(&LOCK_kms);

  if (parse_and_set_kms_config_data(kms_config_data)) {
    mysql_mutex_unlock(&LOCK_kms);
    return 1;
  }

  (*(const char **) save) = value->val_str(value, buff, &len);

  mysql_mutex_unlock(&LOCK_kms);

  /* Remove old kms config data */
  mysql_key_remove<keyring_kms::Key>(kms_config_key_id, nullptr,
                                     "keyring_kms");

  if (mysql_key_store<keyring_kms::Key>(kms_config_key_id,
                                        kms_config_key_type, nullptr,
                                        const_cast<char*>(kms_config_data.c_str()),
                                        kms_config_data.length(),
                                        "keyring_kms")) {
    return 1;
  }

  return 0;
}

/** Update kms config data variable
@param[in] thd      mysql thread instance
@param[in] var      variable
@param[in] var_ptr  variable value
@param[in] save_ptr saved value */
void update_kms_config_data(MYSQL_THD thd  MY_ATTRIBUTE((unused)),
                            SYS_VAR *var  MY_ATTRIBUTE((unused)),
                            void *var_ptr MY_ATTRIBUTE((unused)),
                            const void *save_ptr) {
  const char *kms_config_value = *static_cast<const char*const*>(save_ptr);
  char       *old = *(char**) var_ptr;

  mysql_mutex_lock(&LOCK_kms);

  if (kms_config_value != nullptr) {
    *(char**) var_ptr =  my_strdup(PSI_INSTRUMENT_ME, kms_config_value,  MYF(0));
  } else {
    *(char**) var_ptr = nullptr;
  }

  if (old != nullptr) {
    my_free(old);
  }

  mysql_mutex_unlock(&LOCK_kms);
}

/** Check if current kms config works
@param[in]  thd   mysql thread instance, unused
@param[in]  var   variable, unused
@param[out] save  saved value, unused
@param[in]  value original value, unused
@return 0 on success, 1 on failure */
int check_kms_config(MYSQL_THD thd  MY_ATTRIBUTE((unused)),
                     SYS_VAR *var  MY_ATTRIBUTE((unused)),
                     void *save  MY_ATTRIBUTE((unused)),
                     st_mysql_value *value MY_ATTRIBUTE((unused))) {
  if (!is_kms_config_set) {
    return 1;
  }

  return(kms_config_check());
}

/** Show kms secret id
@param[in]  thd   mysql thread instance, unused
@param[out] var   variable to show
@param[out] buff  buffer to store variable value
@return 0 always */
int show_kms_secret_id(MYSQL_THD thd MY_ATTRIBUTE((unused)),
                       SHOW_VAR *var,
                       char *buff) {
  strcpy(buff, kms_secret_id.c_str());

  var->type= SHOW_CHAR;
  var->value= buff;

  return 0;
}

/** Show kms secret key
@param[in]  thd   mysql thread instance, unused
@param[out] var   variable to show
@param[out] buff  buffer to store variable value
@return 0 always */
int show_kms_secret_key(MYSQL_THD thd MY_ATTRIBUTE((unused)),
                        SHOW_VAR *var,
                        char *buff) {
  strcpy(buff, kms_secret_key.c_str());

  var->type= SHOW_CHAR;
  var->value= buff;

  return 0;
}

/** Show kms end point
@param[in]  thd   mysql thread instance, unused
@param[out] var   variable to show
@param[out] buff  buffer to store variable value
@return 0 always */
int show_kms_end_point(MYSQL_THD thd MY_ATTRIBUTE((unused)),
                       SHOW_VAR *var,
                       char *buff) {
  strcpy(buff, kms_end_point.c_str());

  var->type= SHOW_CHAR;
  var->value= buff;

  return 0;
}

/** Show kms error
@param[in]  thd   mysql thread instance, unused
@param[out] var   variable to show
@param[out] buff  buffer to store variable value
@return 0 always */
int show_kms_error(MYSQL_THD thd MY_ATTRIBUTE((unused)),
                   SHOW_VAR *var,
                   char *buff) {
  strcpy(buff, kms_error.c_str());

  var->type= SHOW_CHAR;
  var->value= buff;

  return 0;
}

/** Show kms region */
int show_kms_region(MYSQL_THD thd MY_ATTRIBUTE((unused)),
                    SHOW_VAR *var,
                    char *buff) {
  strcpy(buff, kms_region.c_str());

  var->type= SHOW_CHAR;
  var->value= buff;

  return 0;
}

/** List key detail with alias "TXSQL-KMS".
@param[out] metas array of key detail with alias "TXSQL-KMS"
@return  0 on success or non-zero on failure. */
int kms_list_key_detail(std::vector<KeyMetadata> &metas){
  Credential cred = Credential(kms_secret_id , kms_secret_key);

  KmsClient kms_client = KmsClient(cred, kms_region);
  kms_client.SetEndPoint(kms_end_point);

  ListKeyDetailRequest list_key_req = ListKeyDetailRequest();
  list_key_req.SetOffset(0);
  list_key_req.SetLimit(10);
  list_key_req.SetSearchKeyAlias(kms_key_alias);
  list_key_req.SetRole(0);

  auto list_key_res = kms_client.ListKeyDetail(list_key_req);
  if (!list_key_res.IsSuccess()) {
    kms_error = "ListKeyDetail fail:" + list_key_res.GetError().PrintAll();
    logger->log(MY_ERROR_LEVEL, kms_error.c_str());
    return 1;
  }

  ListKeyDetailResponse list_key_rsp = list_key_res.GetResult();
  metas = list_key_rsp.GetKeyMetadatas();

  return 0;
}

/** Create cm key.
@param[out] cm_key_id  newly created  cm key id
@return 0 on success or non-zero on failure. */
int kms_create_cm_key(std::string &cm_key_id) {
  Credential cred = Credential(kms_secret_id, kms_secret_key);

  KmsClient kms_client = KmsClient(cred, kms_region);
  kms_client.SetEndPoint(kms_end_point);

  CreateKeyRequest create_key_req = CreateKeyRequest();
  create_key_req.SetAlias(kms_key_alias);
  create_key_req.SetDescription(kms_key_desc);
  create_key_req.SetKeyUsage(kms_key_usage);

  auto create_key_res = kms_client.CreateKey(create_key_req);
  if (!create_key_res.IsSuccess()) {
    kms_error = "CreateKey fail:" + create_key_res.GetError().PrintAll();
    logger->log(MY_ERROR_LEVEL, kms_error.c_str());
    return 1;
  }

  CreateKeyResponse create_key_rsp = create_key_res.GetResult();
  cm_key_id = create_key_rsp.GetKeyId();

  return 0;
}

/** Search cmkey and create cm key if not found.
@param[out] cm_key_id   searched or newly created cm key id
@return 0 on success or non-zero on failure. */
int kms_search_and_create_cm_key(std::string &cm_key_id) {
  KeyMetadata              key_meta;
  bool                     key_found = false;
  std::vector<KeyMetadata> metas;

  /* 1.list current cm key */
  if (kms_list_key_detail(metas)) {
    return 1;
  }

  /* 2. find cm key */
  for (unsigned int i = 0; i < metas.size(); i++) {
    key_meta = metas[i];
    if (key_meta.GetAlias() == kms_key_alias) {
      key_found = true;
      cm_key_id = key_meta.GetKeyId();
      break;
    }
  }

  /* 3.create cm key if it's not found. */
  if (!key_found) {
    kms_action = "create_key";
    if (kms_create_cm_key(cm_key_id)) {
      return 1;
    }
  }

  DBUG_ASSERT(cm_key_id.length() != 0);

  return 0;
}

/** Create data key.
@param[in]  cm_key_id      cm key
@param[in]  key_len        key length of generated data key
@param[out] encrypted_key  encrypted data key
@return 0 on success or non-zero on failure. */
int kms_generate_data_key(const std::string cm_key_id, const size_t key_len,
                          std::string &encrypted_key) {
  Credential cred = Credential(kms_secret_id, kms_secret_key);

  KmsClient kms_client = KmsClient(cred, kms_region);
  kms_client.SetEndPoint(kms_end_point);

  GenerateDataKeyRequest generate_key_req = GenerateDataKeyRequest();
  generate_key_req.SetKeyId(cm_key_id);
  generate_key_req.SetKeySpec("AES_256");
  generate_key_req.SetNumberOfBytes(key_len);
  generate_key_req.SetEncryptionContext("");

  auto generate_key_res = kms_client.GenerateDataKey(generate_key_req);
  if (!generate_key_res.IsSuccess()) {
    kms_error =  "GenerateDataKey fail:" + generate_key_res.GetError().PrintAll();
    logger->log(MY_ERROR_LEVEL, kms_error.c_str());
    return 1;
  }

  GenerateDataKeyResponse generate_key_rsp = generate_key_res.GetResult();
  encrypted_key = generate_key_rsp.GetCiphertextBlob();

  return 0;
}

/** Encode src to base64 string.
@param[in]  src     source string
@param[in]  length  src length
@return encoded string */
string base64_encode(const unsigned char *src, int length) {
  static const char   *b64c =
      "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

  const unsigned char *p = src;
  string dst;

  while (length) {
    dst += b64c[*p >> 2];
    if (!--length) {
      dst += b64c[(*p & 0x3) << 4];
      dst += "==";
      break;
    }

    dst += b64c[((*p & 0x3) << 4) | (*(p + 1) >> 4)];
    p++;

    if (!--length) {
      dst += b64c[(*p & 0xF) << 2];
      dst += '=';
      break;
    }

    dst += b64c[((*p & 0xF) << 2) | (*(p + 1) >> 6)];
    p++;

    dst += b64c[*p & 0x3F];
    p++, length--;
  }

  return dst;
}

/** Judge whether a char is base64.
 @param[in]  c char to be judged
 @return true if is base64, false if not. */
static inline bool is_base64(unsigned char c) {
  return (isalnum(c) || (c == '+') || (c == '/'));
}

/** Decode base64 string.
@param[in]  encoded_string
@return decoded string */
std::string base64_decode(std::string const& encoded_string) {
  int   in_len = encoded_string.size();
  int   i = 0;
  int   j = 0;
  int   in_ = 0;
  std::string                 ret;
  static const  std::string   base64_chars=
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  unsigned char               char_array_4[4], char_array_3[3];

  while (in_len-- && ( encoded_string[in_] != '=')
         && is_base64(encoded_string[in_])) {
    char_array_4[i++] = encoded_string[in_]; in_++;
    if (i ==4) {
      for (i = 0; i <4; i++) {
        char_array_4[i] = base64_chars.find(char_array_4[i]);
      }

      char_array_3[0] = (char_array_4[0] << 2) + ((char_array_4[1] & 0x30) >> 4);
      char_array_3[1] = ((char_array_4[1] & 0xf) << 4) + ((char_array_4[2] & 0x3c) >> 2);
      char_array_3[2] = ((char_array_4[2] & 0x3) << 6) + char_array_4[3];

      for (i = 0; (i < 3); i++) {
        ret += char_array_3[i];
      }

      i = 0;
    }
  }

  if (i) {
    for (j = i; j <4; j++) {
      char_array_4[j] = 0;
    }

    for (j = 0; j <4; j++) {
      char_array_4[j] = base64_chars.find(char_array_4[j]);
    }

    char_array_3[0] = (char_array_4[0] << 2) + ((char_array_4[1] & 0x30) >> 4);
    char_array_3[1] = ((char_array_4[1] & 0xf) << 4) + ((char_array_4[2] & 0x3c) >> 2);
    char_array_3[2] = ((char_array_4[2] & 0x3) << 6) + char_array_4[3];

    for (j = 0; (j < i - 1); j++) {
      ret += char_array_3[j];
    }
  }

  return ret;
}

/** Encrypt plain text.
@param[in]  plain_key     original plain data key
@param[in]  cm_key_id     cm key id
@param[out] encrypted_key encrypted data key
@return 0 on success or non-zero on failure. */
int kms_encrypt(const std::string plain_key, const std::string cm_key_id,
                std::string &encrypted_key) {
  Credential cred = Credential(kms_secret_id, kms_secret_key);

  KmsClient kms_client = KmsClient(cred, kms_region);
  kms_client.SetEndPoint(kms_end_point);

  EncryptRequest encrypt_req = EncryptRequest();
  std::string plain_key_base64;
  plain_key_base64 =
      base64_encode(reinterpret_cast<const unsigned char *>(plain_key.c_str()),
		    plain_key.length());

  encrypt_req.SetKeyId(cm_key_id);
  encrypt_req.SetPlaintext(plain_key_base64);

  auto encrypt_res = kms_client.Encrypt(encrypt_req);
  if (!encrypt_res.IsSuccess()) {
    kms_error = "Encrypt fail:" + encrypt_res.GetError().PrintAll();
    logger->log(MY_ERROR_LEVEL, kms_error.c_str());
    return 1;
  }

  EncryptResponse encrypt_rsp = encrypt_res.GetResult();
  encrypted_key = encrypt_rsp.GetCiphertextBlob();

  return 0;
}

/** Decrypt encrypted text, and decode with base64.
@param[in]  encrypted_key  encrypted data key
@param[out] plain_key      decrypted and base64 decoded data key
@return 0 on success or non-zero on failure. */
int kms_decrypt(const std::string encrypted_key, std::string &plain_key) {
  Credential cred = Credential(kms_secret_id, kms_secret_key);

  KmsClient kms_client = KmsClient(cred, kms_region);
  kms_client.SetEndPoint(kms_end_point);

  DecryptRequest decrypt_req = DecryptRequest();
  decrypt_req.SetCiphertextBlob(encrypted_key);
  decrypt_req.SetEncryptionContext("");

  auto decrypt_res = kms_client.Decrypt(decrypt_req);
  if (!decrypt_res.IsSuccess()) {
    kms_error = "Decrypt fail:" + decrypt_res.GetError().PrintAll();
    logger->log(MY_ERROR_LEVEL, kms_error.c_str());
    return 1;
  }

  DecryptResponse decrypt_rsp = decrypt_res.GetResult();
  plain_key = base64_decode(decrypt_rsp.GetPlaintext());

  return 0;
}

/* Check if kms config works. */
int kms_config_check() {
  std::vector<KeyMetadata> metas;
  if (kms_list_key_detail(metas)) {
    return 1;
  }

  return 0;
}

/** keyring kms key generate interface. */
bool  kms_key_generate(const char *key_id, const char *key_type,
                       const char *user_id, size_t key_len)
{
  if (!is_kms_config_set) {
    kms_error = "config is not set.";
    return true;
  }

  /* 1.search and create cm_key_id if needed */
  std::string cm_key_id;
  if (kms_search_and_create_cm_key(cm_key_id)) {
    return true;
  }

  /* 2.generate data key */
  kms_action = "generate_data_key";
  std::string kms_encrypted_key;
  if (kms_generate_data_key(cm_key_id, key_len, kms_encrypted_key)) {
    return true;
  }

  /* 3.store encrypted key in key file */
  return mysql_key_store<keyring_kms::Key>(key_id, key_type, user_id,
                                           kms_encrypted_key.c_str(),
                                           kms_encrypted_key.length(),
                                           "keyring_kms");
}

/** keyring kms key fetch interface
@param[in]  key_id   key id
@param[out] key_type key type
@param[in]  user_id  user id
@parma[out] key      key
@param[out] key_len  key length
@return 0 on success, 1 on failure */
bool kms_key_fetch(const char *key_id, char **key_type, const char *user_id,
                   void **key, size_t *key_len) {
  if (!is_kms_config_set) {
    kms_error = "config is not set.";
    return true;
  }

  *key = nullptr;
  *key_type = nullptr;
  *key_len = 0;

  /* 1.fetch from kms key cache first. */
  if (!key_cache_fetch(key_id, key_type, user_id, key, key_len)) {
    return false;
  }

  void   *encrypted_key = nullptr;
  size_t encrypted_key_len = 0;
  bool   ret;

  /* 2.fetch encrypted key by key id from kerying kms file. */
  ret = mysql_key_fetch<keyring_kms::Key>(key_id, key_type, user_id,
                                          &encrypted_key,
                                          &encrypted_key_len,
                                          "keyring_kms");
  if (ret == true) {
    logger->log(MY_ERROR_LEVEL, "mysql_key_fetch fail");
    return true;
  }

  if (encrypted_key == nullptr) {
    return false;
  }

  string kms_encrypted_key(static_cast<char*>(encrypted_key), encrypted_key_len);
  std::string kms_plain_key;

  /* free memory before decryption to avoid exception handling. */
  my_free(encrypted_key);

  /* 3.decrypt ecnrypted key from kms. */
  kms_action = "decrypt";
  if(kms_decrypt(kms_encrypted_key, kms_plain_key)) {
    return true;
  }

  /* 4.add plain key into kms key cache. */
  key_cache_store(key_id, *key_type, user_id,
                  reinterpret_cast<void*>(const_cast<char *>(kms_plain_key.c_str())),
                  kms_plain_key.length());

  *key_len = kms_plain_key.length();
  *key = my_malloc(PSI_NOT_INSTRUMENTED, *key_len, MYF(MY_WME));
  strncpy(static_cast<char*>(*key), kms_plain_key.c_str(), *key_len);

  return false;
}

/** keyring kms key store interface, unsupported. */
bool kms_key_store(const char *key_id,
                   const char *key_type,
                   const char *user_id,
                   const void *key,
                   size_t key_len) {
  /* 1.search and create cm_key_id if needed */
  std::string cm_key_id;
  if (kms_search_and_create_cm_key(cm_key_id)) {
    return true;
  }

  /* 2.encrypt key with cm key */
  string org_key(static_cast<char*>(const_cast<void *>(key)), key_len);
  string encrypted_key;
  if (kms_encrypt(org_key, cm_key_id, encrypted_key)) {
    return true;
  }

  /* 3.remove from cache first*/
  key_cache_remove(key_id, user_id);

  /*
    4.store encrypted key into keyring file. If key_id exists in keyring kms file,
    mysql_key_store will return true, this semantic is the same with
    keyring_file.
  */
  return mysql_key_store<keyring_kms::Key>(key_id, key_type, user_id,
                                           encrypted_key.c_str(),
                                           encrypted_key.length(),
                                           "keyring_kms");
}

/** keyring kms key remove interface, unsupported. */
bool kms_key_remove(const char *key_id,
                    const char *user_id) {
  key_cache_remove(key_id, user_id);

  return mysql_key_remove<keyring_kms::Key>(key_id, user_id, "keyring_kms");
}
