#include <string>
#include <iostream>
#include "tencentcloud/kms/v20190118/KmsClient.h"

using namespace std;
using namespace TencentCloud;
using namespace TencentCloud::Kms::V20190118;
using namespace TencentCloud::Kms::V20190118::Model;

string user_test_secret_id = "your secret id";
string user_test_secret_key = "your secret key";
string kms_end_point  = "kms.test.tencentcloudapi.com";
string kms_region = "ap-guangzhou";
const string kms_key_alias = "TEST-TXSQL";
const string kms_key_desc = "The key is generated by TXSQL service when transparent data encryption is enabled.";
const string kms_key_usage = "ENCRYPT_DECRYPT";

static inline bool is_base64(unsigned char c) {
  return (isalnum(c) || (c == '+') || (c == '/'));
}

/** Encode to base64 string.
@param[in]  src     source string
@param[in]  length  src length
@return encoded string */
string base64_encode(const unsigned char *src, int length){
  static const char *b64c = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

  string dst;
  const unsigned char * p = src;

  while (length){
    dst += b64c[*p >> 2];
    if (!--length){
	  dst += b64c[(*p & 0x3) << 4];
	  dst += "==";
	  break;
    }

    dst += b64c[((*p & 0x3) << 4) | (*(p + 1) >> 4)];
    p++;

    if (!--length){
	  dst += b64c[(*p & 0xF) << 2];
	  dst += '=';
	  break;
    }

    dst += b64c[((*p & 0xF) << 2) | (*(p + 1) >> 6)];
    p++;

    dst += b64c[*p & 0x3F];
    p++, length--;
  }

  return dst;
}

/** Decode base64 string.
@param[in]  encoded_string
@return decoded string */
std::string base64_decode(std::string const& encoded_string) {
  int   in_len = encoded_string.size();
  int   i = 0;
  int   j = 0;
  int   in_ = 0;
  std::string   ret;
  static const  std::string base64_chars="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  unsigned char char_array_4[4], char_array_3[3];

  while (in_len-- && ( encoded_string[in_] != '=') && is_base64(encoded_string[in_])) {
    char_array_4[i++] = encoded_string[in_]; in_++;
    if (i ==4) {
      for (i = 0; i <4; i++) {
        char_array_4[i] = base64_chars.find(char_array_4[i]);
      }

      char_array_3[0] = (char_array_4[0] << 2) + ((char_array_4[1] & 0x30) >> 4);
      char_array_3[1] = ((char_array_4[1] & 0xf) << 4) + ((char_array_4[2] & 0x3c) >> 2);
      char_array_3[2] = ((char_array_4[2] & 0x3) << 6) + char_array_4[3];

      for (i = 0; (i < 3); i++) {
        ret += char_array_3[i];
      }

      i = 0;
    }
  }

  if (i) {
    for (j = i; j <4; j++) {
      char_array_4[j] = 0;
    }

    for (j = 0; j <4; j++) {
      char_array_4[j] = base64_chars.find(char_array_4[j]);
    }

    char_array_3[0] = (char_array_4[0] << 2) + ((char_array_4[1] & 0x30) >> 4);
    char_array_3[1] = ((char_array_4[1] & 0xf) << 4) + ((char_array_4[2] & 0x3c) >> 2);
    char_array_3[2] = ((char_array_4[2] & 0x3) << 6) + char_array_4[3];

    for (j = 0; (j < i - 1); j++) {
      ret += char_array_3[j];
    }
  }

  return ret;
}

/** Decrypt encrypted text, and decode with base64.
@param[in]  encrypted_key  encrypted data key
@param[out] plain_key decrypted and base64 decoded data key
@return 0 on success or non-zero on failure. */
int kms_decrypt(const std::string encrypted_key, std::string &plain_key) {
  Credential cred = Credential(user_test_secret_id, user_test_secret_key);

  KmsClient kms_client = KmsClient(cred, kms_region);
  kms_client.SetEndPoint(kms_end_point);

  DecryptRequest decrypt_req = DecryptRequest();
  decrypt_req.SetCiphertextBlob(encrypted_key);
  decrypt_req.SetEncryptionContext("");

  auto decrypt_res = kms_client.Decrypt(decrypt_req);
  if (!decrypt_res.IsSuccess()) {
	cout << "Decrypt fail: " << decrypt_res.GetError().PrintAll() << endl;
    return 1;
  }

  DecryptResponse decrypt_rsp = decrypt_res.GetResult();
  plain_key = base64_decode(decrypt_rsp.GetPlaintext());

  return 0;
}

/** Encrypt plain text.
@param[in]  plain_key     encrypted data key
@param[in]  cm_key_id     cm key id
@param[out] encrypted_key decrypted and base64 decoded data key
@return 0 on success or non-zero on failure. */
int kms_encrypt(const std::string plain_key, const std::string cm_key_id, std::string &encrypted_key) {
  Credential cred = Credential(user_test_secret_id, user_test_secret_key);

  KmsClient kms_client = KmsClient(cred, kms_region);
  kms_client.SetEndPoint(kms_end_point);

  EncryptRequest encrypt_req = EncryptRequest();
  encrypt_req.SetKeyId(cm_key_id);
  encrypt_req.SetPlaintext(plain_key);

  auto encrypt_res = kms_client.Encrypt(encrypt_req);
  if (!encrypt_res.IsSuccess()) {
    cout << "Encrypt fail: " << encrypt_res.GetError().PrintAll() << endl;
    return 1;
  }

  EncryptResponse encrypt_rsp = encrypt_res.GetResult();
  encrypted_key = encrypt_rsp.GetCiphertextBlob();

  return 0;
}

/** List key detail with alias "TEST-CDB".
@param[out] metas array of key detail with alias "TEST-CDB"
@return  0 on success or non-zero on failure. */
int kms_list_key_detail(std::vector<KeyMetadata> &metas){
  Credential cred = Credential(user_test_secret_id , user_test_secret_key);

  KmsClient kms_client = KmsClient(cred, kms_region);
  kms_client.SetEndPoint(kms_end_point);

  ListKeyDetailRequest list_key_req = ListKeyDetailRequest();
  list_key_req.SetOffset(0);
  list_key_req.SetLimit(10);
  list_key_req.SetSearchKeyAlias(kms_key_alias);
  list_key_req.SetRole(0);

  auto list_key_res = kms_client.ListKeyDetail(list_key_req);
  if (!list_key_res.IsSuccess()) {
    cout << "ListKeyDetail fail:" << list_key_res.GetError().PrintAll() << endl;
    return 1;
  }

  ListKeyDetailResponse list_key_rsp = list_key_res.GetResult();
  metas = list_key_rsp.GetKeyMetadatas();

  return 0;
}

/** Create cm key.
@param[out] cm_key_id   cm key id
@return 0 on success or non-zero on failure. */
int kms_create_cm_key(std::string cm_key_id) {
  Credential cred = Credential(user_test_secret_id, user_test_secret_key);

  KmsClient kms_client = KmsClient(cred, kms_region);
  kms_client.SetEndPoint(kms_end_point);

  CreateKeyRequest create_key_req = CreateKeyRequest();
  create_key_req.SetAlias(kms_key_alias);
  create_key_req.SetDescription(kms_key_desc);
  create_key_req.SetKeyUsage(kms_key_usage);

  auto create_key_res = kms_client.CreateKey(create_key_req);
  if (!create_key_res.IsSuccess()) {
    cout << "CreateKey fail:" << create_key_res.GetError().PrintAll() << endl;
    return 1;
  }

  CreateKeyResponse create_key_rsp = create_key_res.GetResult();
  cm_key_id = create_key_rsp.GetKeyId();

  return 0;
}


int main()
{
  std::vector<KeyMetadata> metas;
  if (kms_list_key_detail(metas)) {
    return 1;
  }

  KeyMetadata key_meta;
  bool key_found = false;
  std::string cm_key_id;

  for (unsigned int i = 0; i < metas.size(); i++) {
    key_meta = metas[i];
    if (key_meta.GetAlias() == kms_key_alias) {
      key_found = true;
      cm_key_id = key_meta.GetKeyId();
      break;
    }
  }

  /* 1.create key if it's not found. */
  if (!key_found) {
    if (kms_create_cm_key(cm_key_id)) {
      return 1;
    }
  }

  /* 2.encrypt key */
  std::string plain_key = "nihao";
  std::string encrypt_key;
  std::string base64_plain_ley;

  base64_plain_ley = base64_encode(reinterpret_cast<const unsigned char *>(plain_key.c_str()), plain_key.length());
  if(kms_encrypt(base64_plain_ley, cm_key_id, encrypt_key)) {
	return 1;
  }

  /* 3.decrypt key */
  std::string decrypt_key;
  if(kms_decrypt(encrypt_key, decrypt_key)) {
	return 1;
  }

  /*4.compare decrypted key and orignal key*/
  if(plain_key.compare(decrypt_key)){
	cout << "Decrypted key is not the same as orginal. Orginal: " << plain_key << " Decrypt: " << decrypt_key;
	return 1;
  } else {
	cout << "Decrypted key is the same as orginal. Orginal: " << plain_key << " Decrypt: " << decrypt_key;  
  }

  return 0;
}

