/* Copyright (c) 2009, 2017, Oracle and/or its affiliates. All rights reserved.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License, version 2.0,
   as published by the Free Software Foundation.

   This program is also distributed with certain software (including
   but not limited to OpenSSL) that is licensed under separate terms,
   as designated in a particular file or component or in included license
   documentation.  The authors of MySQL hereby grant you an additional
   permission to link the program and your derivative works with the
   separately licensed software that they have included with MySQL.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License, version 2.0, for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA */

#ifndef PX_DFO_INCLUDED
#define PX_DFO_INCLUDED

#include "sql/iterators/row_iterator.h"  // RowIterator
#include "sql/sql_class.h"  // THD
#include "prealloced_array.h"  // Prealloced_array
#include "px_exchange_info.h"  // PX_exchange_info
#include <unordered_map>

enum dfo_type{NO_TYPE_DFO = 0, LEAF_DFO, INTERNAL_DFO, ROOT_DFO};

/**
  One Dfo is a Dataflow Operator which can be parallely executed, now we split
  the physical iterators by PX_Send iterator and root iterator.

  A Dfo tree is generated by traversing the iterator tree and do split, it has
  children dfos which contruct the tree structure.
*/
class Dfo {
 public:
  Dfo() : m_dfo_type(NO_TYPE_DFO), m_finished(false), m_active(false),
    m_dfo_id(0), m_root_iterator(nullptr), m_parent_dfo(nullptr),
    m_left_most(false), m_child_dfos(4), m_px_scan_ctx(nullptr) {}
  ~Dfo() {}

  void set_dfo_type(dfo_type type) { m_dfo_type = type; }
  void set_dfo_finished(bool finish) { m_finished = finish; }
  void set_dfo_active() { m_active = true; }
  void set_dfo_id(int64_t dfo_counter_id) { m_dfo_id = dfo_counter_id; }
  void set_dfo_dop(int64_t dop) { m_dop = dop; } 
  void set_root_iterator(RowIterator *root) { m_root_iterator = root; }
  void set_parent_dfo(Dfo *dfo) { m_parent_dfo = dfo; }
  void set_left_most() { m_left_most = true; }
  void add_child_dfo(Dfo *dfo) { m_child_dfos.push_back(dfo); }

  bool is_root_dfo() const { return m_dfo_type == ROOT_DFO; }
  bool is_leaf_dfo() const { return m_dfo_type == LEAF_DFO; }
  bool is_internal_dfo() const { return m_dfo_type == INTERNAL_DFO; }
  bool is_dfo_finished() const { return m_finished; }
  bool is_dfo_active() const { return m_active; }
  int64_t dfo_id() const { return m_dfo_id; }
  int64_t dop() const { return m_dop; }
  RowIterator *root_iterator() const { return m_root_iterator; }
  Dfo *parent_dfo() const { return m_parent_dfo; }
  bool left_most() const { return m_left_most; }

 private:
  dfo_type m_dfo_type;  // dfo type{leaf, internal, root}
  bool m_finished;  // has finished already.
  bool m_active;  // still active dfo, still executing.
  int64_t m_dfo_id;  // dfo id.
  int64_t m_dop;  // dop of this dfo.
  RowIterator *m_root_iterator;  // root iterator.
  Dfo *m_parent_dfo;  // parent dfo.
  bool m_left_most; // left most child.

 public:
  Prealloced_array<Dfo*, 4> m_child_dfos;  // children dfos.
  void *m_px_scan_ctx{nullptr};  // px scan ctx.
};

/**
  Dfo manager split iterator by PX_Send and root iterator, A dfo tree generated
  by splitting, the normalization step should be added to adjust mysql-specific
  execution logic.

  mainly include three steps:
  1. Split dfo tree by PX_receiver and PX_sender;
  2. Allocate resource for receiver and sender;
  3. Set sychronization for iterator tree;
*/
class Dfo_mgr {
 public:
  Dfo_mgr(THD *thd) : m_root_dfo(nullptr), m_thd(thd),
    m_root_iterator(nullptr), m_dfo_id_counter(0) {}

  ~Dfo_mgr() {
    for (auto &itr : m_normalized_dfo_tree)
      destroy(itr);
    m_normalized_dfo_tree.clear();
    m_dfos_hash.clear();
  }

  /**
    Split the iterator tree into DFOs' tree by exchange consumer pointer of the
    iterator tree. The DFO tree is original which need to normalize and reorder
    to schedule.

    @param iterator execution iterator tree.
    @param parent_dfo parent dfo
    @return false success, true fail.
  */
  bool do_split(RowIterator *parent_iterator,
         RowIterator *iterator, Dfo *&parent_dfo);

  /**
    Get the ready dfos array which has only two elements, a child and a parent.

    @param dfos out argument
    @return true error, false success
  */
  bool get_ready_dfos(std::vector<Dfo*> &dfos) const;

  /**
    Analyze the iterator tree and do a simple resource allocation, create
    every PX_exchange_info when meet with PX_receiver iterator.
    At last, we set the synchronization topology for the dfo tree.

    @param cores out argument
    @return true error, false success
  */
  bool analyze_resource_allocation(int64_t *cores = nullptr);

 public:
  Dfo *root_dfo() const { return m_root_dfo; }

 public:
  Dfo* m_root_dfo; // Dfo tree which generate this SQL.
  std::vector<Dfo*> m_normalized_dfo_tree;  // dfo array which post order.
  std::unordered_map<int64_t, Dfo*> m_dfos_hash;  // dfo hash table.

 private:
  /**
    create dfo for certain iterator tree.

    @param iterator iterator tree
    @param dfo out argument
    @return true error, false success
  */
  bool create_dfo(RowIterator *iterator, Dfo *&dfo);

  /**
    @brief Create a exchange info between sender and receiver.

    @param dfo_id PX dfo id.
    @param iterator PX receiver iterator.
    @return true error, false success
   */
  bool create_exchange_info(int64_t dfo_id, RowIterator *iterator,
      int64_t producer_dfo_id, int64_t consumer_dfo_id);

 private:
  THD *m_thd; // THD handle.
  RowIterator *m_root_iterator;  // root iterator of the SQL.
  int64_t m_dfo_id_counter; // counter id for all dfo.
  bool m_trx_inited{false};
};

TableRowIterator *analyze_parallel_table(Dfo *dfo);

bool px_partition(THD *thd, const TableRowIterator *scan, size_t &dop,
                  void *&scan_ctx, void *&trx);

#endif  // PX_DFO_INCLUDED
