/* Copyright (c) 2009, 2017, Oracle and/or its affiliates. All rights reserved.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License, version 2.0,
   as published by the Free Software Foundation.

   This program is also distributed with certain software (including
   but not limited to OpenSSL) that is licensed under separate terms,
   as designated in a particular file or component or in included license
   documentation.  The authors of MySQL hereby grant you an additional
   permission to link the program and your derivative works with the
   separately licensed software that they have included with MySQL.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License, version 2.0, for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA */

#ifndef PX_DFO_INCLUDED
#define PX_DFO_INCLUDED

#include "sql/iterators/row_iterator.h"  // RowIterator
#include "sql/sql_class.h"  // THD
#include "prealloced_array.h"  // Prealloced_array

/**
  One Dfo is a Dataflow Operator which can be parallely executed, now we split
  the physical iterators by PX_Send iterator and root iterator.

  A Dfo tree is generated by traversing the iterator tree and do split, it has
  children dfos which contruct the tree structure.
*/
struct Dfo {
  Dfo()
    : m_is_root_dfo(false),
      m_has_scan(false),
      m_finished(false),
      m_active(false),
      m_child_dfos(4),
      m_dfo_id(0),
      m_root_iterator(nullptr),
      m_sender(nullptr),
      m_receiver(nullptr),
      m_join(nullptr),
      m_task_id(-1) {}
  
  bool m_is_root_dfo;  // Whether is root dfo.
  bool m_has_scan;  // leaf node dfo.
  bool m_finished;  // has finished already.
  bool m_active;  // still active dfo, still executing.
  Prealloced_array<Dfo*, 4> m_child_dfos;  // children dfos.
  int64_t m_dfo_id;  // dfo id.
  RowIterator *m_root_iterator;  // root iterator.
  RowIterator *m_sender, *m_receiver; // sender and receiver.
  Dfo *m_parent_dfo;  // parent dfo.
  JOIN *m_join;  // join
  int m_task_id;  // task id info.

  void set_parent_dfo(Dfo *dfo) { m_parent_dfo = dfo; }
  void add_child_dfo(Dfo *dfo) { m_child_dfos.push_back(dfo); }

  void set_dfo_finished() { m_finished = true; }
  bool is_dfo_finished() const { return m_finished; }
  void set_dfo_active() { m_active = true; }
  bool is_dfo_active() const { return m_active; }
  void set_dfo_has_scan() { m_has_scan = true; }
  bool is_dfo_has_scan() const { return m_has_scan; }
};

/**
  Dfo manager split iterator by PX_Send and root iterator, A dfo tree generated
  by splitting, the normalization step should be added to adjust mysql-specific
  execution logic.
*/
class Dfo_mgr {
 public:
  Dfo_mgr(THD *thd)
    : m_root_dfo(nullptr),
      m_thd(thd),
      m_root_iterator(nullptr),
      m_dfo_id_counter(0) {}

  /**
    Split the iterator tree into DFOs' tree by exchange consumer pointer of the
    iterator tree. The DFO tree is original which need to normalize and reorder
    to schedule.

    @param iterator execution iterator tree.
    @param parent_dfo parent dfo
    @return false success, true fail.
  */
  bool do_split_iterator_tree(RowIterator *iterator, Dfo *&parent_dfo);

  /**
    Get the ready dfos array which has only two elements, a child and a parent.

    @param dfos out argument
    @return true error
    @return false success
  */
  bool get_ready_dfos(std::vector<Dfo*> &dfos) const;

  /**
    Normalize the DFO tree and reorder them to schedule, by using the following
    rules:
  */
  void normalize_dfo_tree() {}

  Dfo *root_dfo() const { return m_root_dfo; }

 public:
  std::vector<Dfo*> m_dfos;
  Dfo* m_root_dfo;

 private:
  /**
    create dfo for certain iterator tree.

    @param join join structure of the whole plan
    @param iterator iterator treee
    @param dfo out argument
    @return true error, false success
  */
  bool create_dfo(JOIN *join, RowIterator *iterator, Dfo *&dfo);

 private:
  THD *m_thd;
  RowIterator *m_root_iterator;
  int64_t m_dfo_id_counter;  // dfo id.
};

#endif  // PX_DFO_INCLUDED