/* Copyright (c) 2000, 2020, Oracle and/or its affiliates.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License, version 2.0,
   as published by the Free Software Foundation.

   This program is also distributed with certain software (including
   but not limited to OpenSSL) that is licensed under separate terms,
   as designated in a particular file or component or in included license
   documentation.  The authors of MySQL hereby grant you an additional
   permission to link the program and your derivative works with the
   separately licensed software that they have included with MySQL.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License, version 2.0, for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA */

/**
  @file

  @brief
  This file defines all copy functions for parallel query.
*/

#include "sql/parallel_execution/px_item.h"

#include "sql/item.h"
#include "sql/item_sum.h"
#include "sql/sql_optimizer.h"
#include "sql/sql_executor.h"
#include "sql/log.h"

/**
  Check aggregation functype are in PQ_SUPPORT_AGGR_FUNC
  or not.

  @param type

  @return false if it's in PQ_SUPPORT_AGGR_FUNC.
*/
bool pq_support_aggr_functype(Item_sum::Sumfunctype type) {
  for (auto sum_type : PQ_SUPPORT_AGGR_FUNC) {
    if (sum_type == type) return false;
  }
  return true;
}

/**
  Check whether there is not supportted aggregation function
  or not.

  @param thd
  @param join

  @return false if all functions in sum_funcs are supportted.
*/
bool check_sum_func_support(THD *thd, JOIN *join) {
  // refuse rollup
  if (join->rollup_state != JOIN::RollupState::NONE) {
    return true;
  }
  // refuse none-support sum_funcs
  for (Item_sum **sum_item = join->sum_funcs; *sum_item != nullptr; ++sum_item) {
    const Item_sum::Sumfunctype sum_type = (*sum_item)->sum_func();
    if (pq_support_aggr_functype(sum_type)) return true;
  }
  return false;
}

bool Item::pq_copy_item(THD *thd, Query_block *select, Item *item) {
  cmp_context = item->cmp_context;
  marker = item->marker;

  collation = item->collation;
  item_name.copy(item->item_name.ptr(), item->item_name.length(),
                 system_charset_info, item->item_name.is_autogenerated());
  orig_name.copy(item->orig_name.ptr(), item->orig_name.length(),
                 system_charset_info, item->orig_name.is_autogenerated());
  decimals = item->decimals;
  derived_used = item->derived_used;
  is_expensive_cache = item->is_expensive_cache;
  m_accum_properties = item->m_accum_properties;
  m_data_type = item->m_data_type;
  m_is_window_function = item->m_is_window_function;
  max_length = item->max_length;
  null_value = item->null_value;
  str_value = item->str_value;
  hidden = item->hidden;

#ifndef NDEBUG
  contextualized = item->contextualized;
#endif
  unsigned_flag = item->unsigned_flag;

  return false;
}

bool Item_sum::pq_copy_item(THD *thd, Query_block *select, Item *item) {
  if (Item_result_field::pq_copy_item(thd, select, item)) {
    return true;
  }

  Item_sum *orig_item = dynamic_cast<Item_sum *>(item);
  assert(orig_item);

  if (orig_item != nullptr) {
    m_window = orig_item->m_window;
    m_window_resolved = orig_item->m_window_resolved;
    force_copy_fields = orig_item->force_copy_fields;
    with_distinct = orig_item->with_distinct;
    max_aggr_level = orig_item->max_aggr_level;
    max_sum_func_level = orig_item->max_sum_func_level;
    allow_group_via_temp_table = orig_item->allow_group_via_temp_table;
    save_deny_window_func = orig_item->save_deny_window_func;
    used_tables_cache = orig_item->used_tables_cache;
    forced_const = orig_item->forced_const;

    // need to change the Item_sum in Aggregator, so we should rebuild aggr
    Aggregator *saved_aggr = orig_item->aggr;
    if(this->set_aggregator(saved_aggr->Aggrtype())) {
      return true;
    }
  }

  return false;
}

bool Item_sum_num::pq_copy_item(THD *thd, Query_block *select, Item *item) {
  if (Item_sum::pq_copy_item(thd, select, item)) {
    return true;
  }

  Item_sum_num *orig_item = dynamic_cast<Item_sum_num *>(item);
  assert(orig_item);

  if (orig_item != nullptr) {
    is_evaluated = orig_item->is_evaluated;
  }

  return false;
}

bool Item_sum_sum::pq_copy_item(THD *thd, Query_block *select, Item *item) {
  if (Item_sum_num::pq_copy_item(thd, select, item)) {
    return true;
  }
  return false;
}

bool Item_sum_max::pq_copy_item(THD *thd, Query_block *select, Item *item) {
  if (Item_sum_hybrid::pq_copy_item(thd, select, item)) {
    return true;
  }
  return false;
}

bool Item_sum_min::pq_copy_item(THD *thd, Query_block *select, Item *item) {
  if (Item_sum_hybrid::pq_copy_item(thd, select, item)) {
    return true;
  }
  return false;
}

bool Item_sum_hybrid::pq_copy_item(THD *thd, Query_block *select, Item *item) {
  if (Item_sum::pq_copy_item(thd, select, item)) {
    return true;
  }

  Item_sum_hybrid *orig_item = dynamic_cast<Item_sum_hybrid *>(item);
  assert(orig_item);

  // todo: copy value or arg_cache

  hybrid_type = orig_item->hybrid_type;
  was_values = orig_item->was_values;
  m_nulls_first = orig_item->m_nulls_first;
  m_optimize = orig_item->m_optimize;
  m_want_first = orig_item->m_want_first;
  m_cnt = orig_item->m_cnt;
  m_saved_last_value_at = orig_item->m_saved_last_value_at;

  return false;
}


Item_sum **Item_sum_count::pq_rebuild_item(THD *thd, Query_block *select) {
  Item_sum **item_sum_list = (Item_sum **) thd->mem_calloc(sizeof(Item_sum **) * 2);
  if (!item_sum_list) {
    return nullptr;
  }
  // create new item for parallel query.
  Item_sum *new_sum_item = new (thd->mem_root) Item_sum_sum(POS(), args[0], has_with_distinct(), m_window);
  if (new_sum_item == nullptr || new_sum_item->pq_copy_item(thd, select, this)) {
    return nullptr;
  }
  item_sum_list[0] = new_sum_item;
  item_sum_list[1] = nullptr; // End marker.
  return item_sum_list;
}

Item_sum **Item_sum_avg::pq_rebuild_item(THD *thd, Query_block *select) {
  Item_sum **item_sum_list = (Item_sum **) thd->mem_calloc(sizeof(Item_sum **) * 3);
  if (!item_sum_list) {
    return nullptr;
  }

  Item_sum *new_sum_item = new (thd->mem_root) Item_sum_sum(POS(), args[0], has_with_distinct(), m_window);
  Item_sum *new_count_item = new (thd->mem_root) Item_sum_count(POS(), args[0], m_window);
  if (new_sum_item == nullptr || new_sum_item->pq_copy_item(thd, select, this)) {
    return nullptr;
  }
  new_sum_item->fix_fields(thd, nullptr);
  item_sum_list[0] = new_sum_item;

  if (new_count_item == nullptr || new_count_item->pq_copy_item(thd, select, this)) {
    return nullptr;
  }
  new_count_item->fix_fields(thd, nullptr);
  item_sum_list[1] = new_count_item;
  item_sum_list[2] = nullptr;

  return item_sum_list;
}

Item_sum **Item_sum_sum::pq_rebuild_item(THD *thd, Query_block *select) {
  Item_sum **item_sum_list = (Item_sum **) thd->mem_calloc(sizeof(Item_sum **) * 2);
  if (!item_sum_list) {
    return nullptr;
  }
  // create new item for parallel query.
  Item_sum *new_sum_item = new (thd->mem_root) Item_sum_sum(POS(), args[0], has_with_distinct(), m_window);
  if (new_sum_item == nullptr || new_sum_item->pq_copy_item(thd, select, this)) {
    return nullptr;
  }
  item_sum_list[0] = new_sum_item;
  item_sum_list[1] = nullptr; // End marker.
  return item_sum_list;
}

Item_sum **Item_sum_max::pq_rebuild_item(THD *thd, Query_block *select) {
  Item_sum **item_sum_list = (Item_sum **) thd->mem_calloc(sizeof(Item_sum **) * 2);
  if (!item_sum_list) {
    return nullptr;
  }
  // create new item for parallel query.
  Item_sum *new_sum_item = new (thd->mem_root) Item_sum_max(POS(), args[0], m_window);
  if (new_sum_item == nullptr || new_sum_item->pq_copy_item(thd, select, this)) {
    return nullptr;
  }
  item_sum_list[0] = new_sum_item;
  item_sum_list[1] = nullptr; // End marker.
  return item_sum_list;
}

Item_sum **Item_sum_min::pq_rebuild_item(THD *thd, Query_block *select) {
  Item_sum **item_sum_list = (Item_sum **) thd->mem_calloc(sizeof(Item_sum **) * 2);
  if (!item_sum_list) {
    return nullptr;
  }
  // create new item for parallel query.
  Item_sum *new_sum_item = new (thd->mem_root) Item_sum_min(POS(), args[0], m_window);
  if (new_sum_item == nullptr || new_sum_item->pq_copy_item(thd, select, this)) {
    return nullptr;
  }
  item_sum_list[0] = new_sum_item;
  item_sum_list[1] = nullptr; // End marker.
  return item_sum_list;
}


void Temp_table_param::pq_copy_from(Temp_table_param *orig_param) {
  skip_create_table = orig_param->skip_create_table;
  group_length = orig_param->group_length;
  table_charset = orig_param->table_charset;
  schema_table = orig_param->schema_table;
  force_copy_fields = orig_param->force_copy_fields;
  bit_fields_as_long = orig_param->bit_fields_as_long;
  group_parts = orig_param->group_parts;
  group_null_parts = orig_param->group_null_parts;
}