/* Copyright (c) 2000, 2020, Oracle and/or its affiliates.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License, version 2.0,
   as published by the Free Software Foundation.

   This program is also distributed with certain software (including
   but not limited to OpenSSL) that is licensed under separate terms,
   as designated in a particular file or component or in included license
   documentation.  The authors of MySQL hereby grant you an additional
   permission to link the program and your derivative works with the
   separately licensed software that they have included with MySQL.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License, version 2.0, for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA */

/**
  @file

  @brief
  This file defines all copy functions for parallel query.
*/

#include "sql/parallel_execution/px_item.h"

#include "sql/parallel_execution/px_access_path.h"

#include "sql/filesort.h"
#include "sql/item.h"
#include "sql/item_sum.h"
#include "sql/sql_optimizer.h"
#include "sql/sql_executor.h"
#include "sql/log.h"

static const char *px_unsafe_func_name[] {
  "rand",          "json_valid",         "json_length",
  "json_type",     "json_contains_path", "json_unquote",
  "st_distance",   "get_lock",           "is_free_lock",
  "is_used_lock",  "release_lock",       "sleep",
  "xml_str",       "json_func",          "release_all_locks"
};

/**
  The compatibility of parallel query compatibility detection for Field is
  divided into two categories:
  1) Parallel scan compatible: fields allowed in the parallel table
  2) Compatible data exchange: the fields allowed by the Exchange operator
     in the data exchange between threads
  Some fields, such as generated columns, are not compatible with parallel scans.
  There are also some fields that are neither compatible with parallel scanning
  nor compatible with data exchange. The current parallel query compatibility
  only considers data exchange compatible checks, ignoring parallel scan compatible checks.

  TODO: the list of px_scan_unsafe_field_type is the same as
  the list of px_xchg_unsafe_field_type at the beginning.
*/
static const enum_field_types px_scan_unsafe_field_type[] = {
  MYSQL_TYPE_GEOMETRY,
  MYSQL_TYPE_BIT
};

static const enum_field_types px_xchg_unsafe_field_type[] {
  MYSQL_TYPE_GEOMETRY,
  MYSQL_TYPE_BIT
};

static const enum_field_types px_lob_field_type[] = {
  MYSQL_TYPE_BLOB, MYSQL_TYPE_TINY_BLOB,
  MYSQL_TYPE_MEDIUM_BLOB, MYSQL_TYPE_LONG_BLOB,
  MYSQL_TYPE_JSON
};

bool Item::pq_copy_item(THD *thd, Query_block *select, Item *item) {
  cmp_context = item->cmp_context;
  marker = item->marker;

  collation = item->collation;
  item_name.copy(item->item_name.ptr(), item->item_name.length(),
                 system_charset_info, item->item_name.is_autogenerated());
  orig_name.copy(item->orig_name.ptr(), item->orig_name.length(),
                 system_charset_info, item->orig_name.is_autogenerated());
  decimals = item->decimals;
  derived_used = item->derived_used;
  is_expensive_cache = item->is_expensive_cache;
  m_accum_properties = item->m_accum_properties;
  m_data_type = item->m_data_type;
  m_is_window_function = item->m_is_window_function;
  max_length = item->max_length;
  null_value = item->null_value;
  str_value = item->str_value;
  hidden = item->hidden;

#ifndef NDEBUG
  contextualized = item->contextualized;
#endif
  unsigned_flag = item->unsigned_flag;

  return false;
}

bool Item_sum::pq_copy_item(THD *thd, Query_block *select, Item *item) {
  if (Item_result_field::pq_copy_item(thd, select, item)) {
    return true;
  }

  Item_sum *orig_item = dynamic_cast<Item_sum *>(item);
  assert(orig_item);

  if (orig_item != nullptr) {
    m_window = orig_item->m_window;
    m_window_resolved = orig_item->m_window_resolved;
    force_copy_fields = orig_item->force_copy_fields;
    with_distinct = orig_item->with_distinct;
    max_aggr_level = orig_item->max_aggr_level;
    max_sum_func_level = orig_item->max_sum_func_level;
    allow_group_via_temp_table = orig_item->allow_group_via_temp_table;
    save_deny_window_func = orig_item->save_deny_window_func;
    used_tables_cache = orig_item->used_tables_cache;
    forced_const = orig_item->forced_const;

    // need to change the Item_sum in Aggregator, so we should rebuild aggr
    Aggregator *saved_aggr = orig_item->aggr;
    if(this->set_aggregator(saved_aggr->Aggrtype())) {
      return true;
    }
  }

  return false;
}

bool Item_sum_num::pq_copy_item(THD *thd, Query_block *select, Item *item) {
  if (Item_sum::pq_copy_item(thd, select, item)) {
    return true;
  }

  Item_sum_num *orig_item = dynamic_cast<Item_sum_num *>(item);
  assert(orig_item);

  if (orig_item != nullptr) {
    is_evaluated = orig_item->is_evaluated;
  }

  return false;
}

bool Item_sum_sum::pq_copy_item(THD *thd, Query_block *select, Item *item) {
  if (Item_sum_num::pq_copy_item(thd, select, item)) {
    return true;
  }
  return false;
}

bool Item_sum_max::pq_copy_item(THD *thd, Query_block *select, Item *item) {
  if (Item_sum_hybrid::pq_copy_item(thd, select, item)) {
    return true;
  }
  return false;
}

bool Item_sum_min::pq_copy_item(THD *thd, Query_block *select, Item *item) {
  if (Item_sum_hybrid::pq_copy_item(thd, select, item)) {
    return true;
  }
  return false;
}

bool Item_sum_hybrid::pq_copy_item(THD *thd, Query_block *select, Item *item) {
  if (Item_sum::pq_copy_item(thd, select, item)) {
    return true;
  }

  Item_sum_hybrid *orig_item = dynamic_cast<Item_sum_hybrid *>(item);
  assert(orig_item);

  // todo: copy value or arg_cache

  hybrid_type = orig_item->hybrid_type;
  was_values = orig_item->was_values;
  m_nulls_first = orig_item->m_nulls_first;
  m_optimize = orig_item->m_optimize;
  m_want_first = orig_item->m_want_first;
  m_cnt = orig_item->m_cnt;
  m_saved_last_value_at = orig_item->m_saved_last_value_at;

  return false;
}


Item_sum **Item_sum_count::pq_rebuild_item(THD *thd, Query_block *select) {
  Item_sum **item_sum_list = (Item_sum **) thd->mem_calloc(sizeof(Item_sum **) * 2);
  if (!item_sum_list) {
    return nullptr;
  }
  // create new item for parallel query.
  Item_sum *new_sum_item = new (thd->mem_root) Item_sum_sum(POS(), args[0], has_with_distinct(), m_window);
  if (new_sum_item == nullptr || new_sum_item->pq_copy_item(thd, select, this)) {
    return nullptr;
  }

  // Sign sum create for count.
  Item_sum_sum *item_sum = down_cast<Item_sum_sum *>(new_sum_item);
  item_sum->pq_set_create_for_count(true);

  item_sum_list[0] = new_sum_item;
  item_sum_list[1] = nullptr; // End marker.
  return item_sum_list;
}

Item_sum **Item_sum_avg::pq_rebuild_item(THD *thd, Query_block *select) {
  Item_sum **item_sum_list = (Item_sum **) thd->mem_calloc(sizeof(Item_sum **) * 3);
  if (!item_sum_list) {
    return nullptr;
  }

  Item_sum *new_sum_item = new (thd->mem_root) Item_sum_sum(POS(), args[0], has_with_distinct(), m_window);
  Item_sum *new_count_item = new (thd->mem_root) Item_sum_count(POS(), args[0], m_window);
  if (new_sum_item == nullptr || new_sum_item->pq_copy_item(thd, select, this)) {
    return nullptr;
  }
  new_sum_item->fix_fields(thd, nullptr);
  item_sum_list[0] = new_sum_item;

  if (new_count_item == nullptr || new_count_item->pq_copy_item(thd, select, this)) {
    return nullptr;
  }
  new_count_item->fix_fields(thd, nullptr);
  item_sum_list[1] = new_count_item;
  item_sum_list[2] = nullptr;

  return item_sum_list;
}

Item_sum **Item_sum_sum::pq_rebuild_item(THD *thd, Query_block *select) {
  Item_sum **item_sum_list = (Item_sum **) thd->mem_calloc(sizeof(Item_sum **) * 2);
  if (!item_sum_list) {
    return nullptr;
  }
  // create new item for parallel query.
  Item_sum *new_sum_item = new (thd->mem_root) Item_sum_sum(POS(), args[0], has_with_distinct(), m_window);
  if (new_sum_item == nullptr || new_sum_item->pq_copy_item(thd, select, this)) {
    return nullptr;
  }
  item_sum_list[0] = new_sum_item;
  item_sum_list[1] = nullptr; // End marker.
  return item_sum_list;
}

Item_sum **Item_sum_max::pq_rebuild_item(THD *thd, Query_block *select) {
  Item_sum **item_sum_list = (Item_sum **) thd->mem_calloc(sizeof(Item_sum **) * 2);
  if (!item_sum_list) {
    return nullptr;
  }
  // create new item for parallel query.
  Item_sum *new_sum_item = new (thd->mem_root) Item_sum_max(POS(), args[0], m_window);
  if (new_sum_item == nullptr || new_sum_item->pq_copy_item(thd, select, this)) {
    return nullptr;
  }
  item_sum_list[0] = new_sum_item;
  item_sum_list[1] = nullptr; // End marker.
  return item_sum_list;
}

Item_sum **Item_sum_min::pq_rebuild_item(THD *thd, Query_block *select) {
  Item_sum **item_sum_list = (Item_sum **) thd->mem_calloc(sizeof(Item_sum **) * 2);
  if (!item_sum_list) {
    return nullptr;
  }
  // create new item for parallel query.
  Item_sum *new_sum_item = new (thd->mem_root) Item_sum_min(POS(), args[0], m_window);
  if (new_sum_item == nullptr || new_sum_item->pq_copy_item(thd, select, this)) {
    return nullptr;
  }
  item_sum_list[0] = new_sum_item;
  item_sum_list[1] = nullptr; // End marker.
  return item_sum_list;
}


void Temp_table_param::pq_copy_from(Temp_table_param *orig_param) {
  skip_create_table = orig_param->skip_create_table;
  group_length = orig_param->group_length;
  table_charset = orig_param->table_charset;
  schema_table = orig_param->schema_table;
  force_copy_fields = orig_param->force_copy_fields;
  bit_fields_as_long = orig_param->bit_fields_as_long;
  group_parts = orig_param->group_parts;
  group_null_parts = orig_param->group_null_parts;
}

/**
  Check if the field type is supported for cross-thread exchange(xchg).

  @see PX_compact_codec::make_compact_field() and
  PX_compact_codec::decompact_field(), the compatibility check of these three
  functions for the types of field should be consistent.

  @return false if supported, true otherwise
*/
static bool check_xchg_safe_field_type(enum_field_types type) {
  THD *cur_thd = current_thd;
  assert(cur_thd);

  for (auto field_type : px_xchg_unsafe_field_type) {
    if (field_type == type) return true;
  }

  /*
    If set txsql_parallel_lob_enabled to true, allow the lob
    field list to pass the parallel compatibility check.
  */
  if (!cur_thd->variables.txsql_parallel_lob_enabled) {
    for (auto field_type : px_lob_field_type) {
      if (field_type == type) return true;
    }
  }

  return false;
}

static bool check_parallel_scan_safe_field_type(enum_field_types type) {
  THD *cur_thd = current_thd;
  assert(cur_thd);

  for (auto field_type : px_scan_unsafe_field_type) {
    if (field_type == type) return true;
  }

  /*
    If set txsql_parallel_lob_enabled to true, allow the lob
    field list to pass the parallel compatibility check.
  */
  if (!cur_thd->variables.txsql_parallel_lob_enabled) {
    for (auto field_type : px_lob_field_type) {
      if (field_type == type) return true;
    }
  }

  return false;
}

/**
  Check if field is supported for cross-thread exchange(xchg).
  @return false if supported, true otherwise
*/
bool check_xchg_unsafe_field(const Field *field) {
  assert(field);

  if (check_xchg_safe_field_type(field->type())) {
    return true;
  }

  return false;
}

/**
  Check whether the field is supported in parallel scan.
  @return false if supported, true otherwise
*/
bool check_parallel_scan_unsafe_field(const Field *field) {
  assert(field);

  if (field->is_gcol()) {
    return true;
  }

  if (check_parallel_scan_safe_field_type(field->type())) {
    return true;
  }

  return false;
}

/**
  Check the data type of the item is supported for cross-thread exchange.(xchg)
  @return false if compatible, true otherwise
*/
static bool check_xchg_unsafe_datatype(Item *item) {
  assert(item);

  if (check_xchg_safe_field_type(item->data_type())) {
    return true;
  }

  // The data_type of item_field is the same as the type of field. see
  // Item_field::set_field()
  assert(item->type() != Item::FIELD_ITEM ||
              item->data_type() ==
                  static_cast<Item_field *>(item)->field->type());

  Field *tmp_field = nullptr;
  if ((tmp_field = item->get_tmp_table_field())) {
    if (check_xchg_unsafe_field(tmp_field)) return true;
  }

  return false;
}

static bool check_px_unsafe_aggr_func(Item *item) {
  assert(item);

  if (item->type() == Item::SUM_FUNC_ITEM) {
    Item_sum *aggr = static_cast<Item_sum *>(item);
    /* Check parallel safe of the Item_sum */
    if (!aggr->parallel_safe()) {
      return true;
    }

    for (uint i = 0; i < aggr->arg_count; i++) {
      Item *arg_item = aggr->get_arg(i);
      assert(arg_item);
      if (!arg_item || check_px_unsafe_item(arg_item)) {
        return true;
      }
    }
  }

  return false;
}

static bool check_px_unsafe_func(Item *item) {
  assert(item);

  if (item->type() == Item::FUNC_ITEM) {
    Item_func *func = static_cast<Item_func *>(item);

    // Check parallel unsafe by func type
    if (func->functype() == Item_func::UDF_FUNC ||
        func->functype() == Item_func::FUNC_SP) {
      // Querys that contain these type of function should be intercepted by
      // LEX::check_px_execution()
      assert(0);
      return true;
    }
    if (func->functype() == Item_func::JSON_FUNC ||
        func->functype() == Item_func::XML_FUNC ||
        func->functype() == Item_func::SUSERVAR_FUNC ||
        func->functype() == Item_func::MATCH_FUNC) {
      return true;
    }

    // Check parallel unsafe by func name
    for (auto funcname : px_unsafe_func_name) {
      if (!strcmp(func->func_name(), funcname)) {
        return true;
      }
    }

    for (uint i = 0; i < func->arg_count; i++) {
      Item *arg_item = func->get_arg(i);
      assert(arg_item);
      if (!arg_item || check_px_unsafe_item(arg_item)) {
        return true;
      }
    }
  }

  return false;
}

static bool check_px_unsafe_cond(Item *item) {
  assert(item);

  if (item->type() == Item::COND_ITEM) {
    Item_cond *condition = static_cast<Item_cond *>(item);

    // Check parallel unsafe by func type
    if (condition->functype() == Item_func::UDF_FUNC ||
        condition->functype() == Item_func::FUNC_SP) {
      // Querys that contain these type of function should be intercepted by
      // LEX::check_px_execution()
      assert(0);
      return true;
    }
    if (condition->functype() == Item_func::JSON_FUNC ||
        condition->functype() == Item_func::XML_FUNC ||
        condition->functype() == Item_func::SUSERVAR_FUNC ||
        condition->functype() == Item_func::MATCH_FUNC) {
      return true;
    }

    Item *arg_item = nullptr;
    List_iterator_fast<Item> it(*condition->argument_list());
    for (uint i = 0; (arg_item = it++); i++) {
      assert(arg_item);
      if (!arg_item || check_px_unsafe_item(arg_item)) {
        return true;
      }
    }
  }

  return false;
}

static bool check_px_unsafe_ref(Item *item) {
  assert(item);
  if (item->type() == Item::REF_ITEM) {
    Item_ref *item_ref = down_cast<Item_ref *>(item);
    if (!item_ref ||
        item_ref->ref_type() == Item_ref::OUTER_REF) {
      return true;
    }

    if (item_ref->ref[0] && check_px_unsafe_item(item_ref->ref[0])) {
      return true;
    }
  }

  return false;
}

static bool check_px_unsafe_row(Item *item) {
  assert(item);

  if (item->type() == Item::ROW_ITEM) {
    Item_row *row = down_cast<Item_row *>(item);

    for (uint i = 0; i < row->cols(); i++) {
      Item *row_item = row->element_index(i);
      assert(row_item);
      if (!row_item || check_px_unsafe_item(row_item)) {
        return true;
      }
    }
  }

  return false;
}

static bool check_px_unsafe_cache(Item *item) {
  assert(item);

  if (item->type() == Item::CACHE_ITEM) {
    Item_cache *cache = dynamic_cast<Item_cache *>(item);

    Item *example = cache->get_example();
    assert(example);
    if (!example || check_px_unsafe_item(example)) {
      return true;
    }
  }

  return false;
}

static bool check_px_unsafe_subselect(Item *item) {
  assert(item);

  if (item->type() == Item::SUBSELECT_ITEM) {
    Item_subselect *subselect = down_cast<Item_subselect *>(item);
    Query_expression *unit = subselect->unit;
    // Subselect may not have been optimized here, see Item_subselect::exec().
    if (!unit->is_optimized() || !unit->root_access_path()) {
      return true;
    }
    JOIN *join = unit->fake_query_block ? unit->fake_query_block->join
                                       : unit->first_query_block()->join;
    AccessPath *max_subtree = nullptr;
    bool exchange_safe = false;
    bool is_stream = false;
    uint ref_slice = REF_SLICE_SAVED_BASE;
    return !px_access_path::WalkAccessPathsForCompat(
        current_thd, unit->root_access_path(), nullptr, join,
        /*parallel_scan=*/false, /*root=*/true, /*root_all=*/false, ref_slice,
        max_subtree, is_stream, nullptr, nullptr, exchange_safe);
  }

  return false;
}

/**
  Check the data type of the func_ptr is supported for cross-thread
  exchange(xchg).
  @return false if compatible, true otherwise
*/
static bool check_xchg_unsafe_func_ptr(Func_ptr *func) {
  Field *result_field = func->override_result_field()
                            ? func->override_result_field()
                            : func->func()->get_result_field();

  if (check_xchg_unsafe_field(result_field) ||
      check_xchg_unsafe_datatype(func->func())) {
    return true;
  }
  return false;
}

/**
  Check the compatibility of items, which may be exchanged by exchange channel.
  @return false if parallel safe, true otherwise.
*/
bool check_px_unsafe_item(Item *item) {
  if (check_px_unsafe_aggr_func(item) ||
      check_px_unsafe_func(item) ||
      check_px_unsafe_cond(item) ||
      check_px_unsafe_ref(item) ||
      check_px_unsafe_row(item) ||
      check_px_unsafe_cache(item) ||
      check_px_unsafe_subselect(item)) {
    return true;
  }

  return false;
}

/**
  Check whether there is not supported aggregation function or not.
  @return false if all functions in sum_funcs are supportted.
*/
bool check_px_unsafe_sum_funcs(JOIN *join) {
  assert(join);
  Item_sum **sum_funcs = join->sum_funcs, *sum_item;
  while ((sum_item = *(sum_funcs++))) {
    if (check_px_unsafe_aggr_func(sum_item)) return true;
  }
  return false;
}

/**
  Check the data type of the sum_func is supported for cross-thread
  exchange(xchg).
  @return false if compatible, true otherwise
*/
bool check_xchg_unsafe_sum_funcs(JOIN *join) {
  assert(join);
  Item_sum **sum_funcs = join->sum_funcs, *sum_item;
  while ((sum_item = *(sum_funcs++))) {
    if (check_xchg_unsafe_datatype(sum_item)) return true;
  }
  return false;
}

/**
 * @return false if parallel safe, true otherwise.
 */
bool check_px_unsafe_projector(JOIN *join) {
  assert(join);
  for (Item *item : *join->fields) {
    if (check_px_unsafe_item(item)) return true;
  }
  return false;
}

/**
 * @return false if parallel safe, true otherwise.
 */
bool check_px_unsafe_group(List<Cached_item> &group_field) {
  List_iterator<Cached_item> li(group_field);
  Cached_item *buff;

  while ((buff = li++)) {
    if (check_px_unsafe_item(buff->get_item())) return true;
  }
  return false;
}

/**
 * @return false if parallel safe, true otherwise.
 */
bool check_px_unsafe_order(JOIN *join, ORDER *order, uint ref_slice) {
  // In case of Item_ref
  if (join && ref_slice) Switch_ref_item_slice ref_item_slice(join, ref_slice);
  for (; order; order = order->next) {
    if (check_px_unsafe_item(*order->item)) return true;
  }
  return false;
}

/**
 * @return false if parallel safe, true otherwise.
 */
bool check_px_unsafe_cond(JOIN *join, Item *cond, uint ref_slice) {
  // In case of Item_ref
  if (join && ref_slice) Switch_ref_item_slice ref_item_slice(join, ref_slice);
  return check_px_unsafe_item(cond);
}

/**
 * @return false if parallel safe, true otherwise.
 */
bool check_px_unsafe_temp_param(const Temp_table_param *param) {
  if (!param) return false;

  if (!param->items_to_copy || !param->items_to_copy->size()) {
    return false;
  }

  Func_ptr_array *func_ptr = param->items_to_copy;
  uint end = func_ptr->size();
  for (uint i = 0; i < end; i++) {
    Func_ptr *func = &func_ptr->at(i);
    if (check_px_unsafe_func(func->func())) return true;
  }
  return false;
}

/**
  Check the data type of the items is supported for cross-thread exchange(xchg).
  @return false if compatible, true otherwise
*/
bool check_xchg_unsafe_temp_param(const Temp_table_param *param) {
  if (!param) return false;
  /*
  for (Item_copy *item_copy : param->grouped_expressions) {
    if (check_xchg_unsafe_datatype(item_copy->get_item())) return true;
  }
  */
  for (Copy_field copy_field : param->copy_fields) {
    if (check_xchg_unsafe_field(copy_field.from_field())) return true;
  }

  if (!param->items_to_copy || !param->items_to_copy->size()) {
    return false;
  }

  Func_ptr_array *func_ptr = param->items_to_copy;
  uint end = func_ptr->size();
  for (uint i = 0; i < end; i++) {
    Func_ptr *func = &func_ptr->at(i);
    if (check_xchg_unsafe_func_ptr(func)) return true;
  }
  return false;
}

bool Temp_table_param::eq(const Temp_table_param *other) const {
  if (!other) {
    return false;
  }

  return (skip_create_table == other->skip_create_table &&
      group_length == other->group_length &&
      schema_table == other->schema_table &&
      force_copy_fields == other->force_copy_fields &&
      bit_fields_as_long == other->bit_fields_as_long &&
      group_parts == other->group_parts &&
      group_null_parts == other->group_null_parts);
}
