/* Copyright (c) 2009, 2017, Oracle and/or its affiliates. All rights reserved.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License, version 2.0,
   as published by the Free Software Foundation.

   This program is also distributed with certain software (including
   but not limited to OpenSSL) that is licensed under separate terms,
   as designated in a particular file or component or in included license
   documentation.  The authors of MySQL hereby grant you an additional
   permission to link the program and your derivative works with the
   separately licensed software that they have included with MySQL.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License, version 2.0, for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA */

#ifndef PX_OPTIMIZER_CONTEXT_INCLUDED
#define PX_OPTIMIZER_CONTEXT_INCLUDED

#include "sql/query_result.h"  // Query_result
#include "mysql/psi/mysql_thread.h"  // mysql_mutex_t

class THD;

/*
  The correctness of parallel execution depends on the consistency
  execution plan between the worker and the coordinator. So that,
  the worker will generate the same DFO like it generated by the
  coordinator.

  Therefore, we need to ensure that the optimizer environment of
  worker threads are consistent with that of the coordinator thread.

  The optimizer environment of the worker thread is copied from
  the coordinator thread. The function copies:
    - THD::variables
    - THD::table_plugin (default_storage_engine)
    - THD::temp_table_plugin (default_tmp_storage_engine)
    - THD::charset
    - THD::user_vars
*/
extern bool post_init_worker_thd(THD *coordinator_thd, THD *worker_thd);

#endif  // PX_OPTIMIZER_CONTEXT_INCLUDED